polymer/src/elements/etools-prp-progress-bar.html, polymer/src/styles/progress-bar.html
Progress bar scaling #92
https://github.com/unicef/etools-partner-reporting-portal/issues/92
+ bar will scale to the size of the column (but with min and max widths)
+ text will never drop below the bar
=> fix: progress bar scaling

polymer/src/behaviors/pagination.html, polymer/src/elements/ip-reporting/list-view-indicators.html
- added function to collapse all details on page number change event
- had to hijack event emitted by pagination element, as new event clashed with this one and I see this as a problem since we will add extra collapsing to page change on every list.
But simply dropping this handler into list-view-indicators.html seems to break the first handler (no request and data update happens)
```
_pageNumberChanged: function () {
document.querySelectorAll('* /deep/ #details').forEach(function (details) {
if (details.opened) details.toggle();
});
}
```
=> Fix: details don't collapse on pagination #123

django_api/django_api/apps/indicator/serializers.py
This PR addresses a new API field called `is_complete` to indicate that location data is complete if any disaggregation data is filled.
* is_complete SerializerMethodField on SimpleIndicatorLocationDataListSerializer
=> Fix - is_complete Flag for IndicatorLocationData [#156]

django_api/django_api/apps/cluster/filters.py, django_api/django_api/apps/cluster/tests/test_views.py, django_api/django_api/apps/cluster/urls.py, django_api/django_api/apps/cluster/views.py, django_api/django_api/apps/partner/filters.py, django_api/django_api/apps/partner/tests/test_views.py, django_api/django_api/apps/partner/urls.py, django_api/django_api/apps/partner/views.py
* Impacts objective, project, cluster activity list screens.
* Remove any endpoints that have cluster_id in them eg. ^api/cluster/ ^(?P<cluster_id>\d+)/cluster-objective-list/$ [name='cluster-objective-list']
=> Rm cluster id #204

polymer/src/elements/form-fields/cluster-dropdown-input.html
Cluster dropdown when creating a cluster objective or activity "All" option is not correct / not needed.
This resolves #231.
PR probably not necessary, but doing it for consistency.
=> Removing 'All' option from the cluster dropdown used in creation modals

polymer/src/pages/app/cluster-reporting/select-plan.html
This PR addresses: Cross-browser problem with radio buttons in Select Plan page
This resolves #253.
If the browser is targeting an element nested in paper-radio-button (FF and Safari), we get the paper-radio-button element instead. The Select Plan page now works in those browsers.
=> Finding parent node of radio button to fix cross-browser issue

polymer/src/behaviors/utils.html, polymer/src/elements/cluster-reporting/planned-action/projects/creation-modal.html, polymer/src/elements/cluster-reporting/project-details.html, polymer/src/elements/cluster-reporting/project-list-table.html, polymer/src/elements/cluster-reporting/response-parameters/clusters/activities/contributing-partners-list.html
+ Changed the Locations and Clusters fields in the Create Project modal to use the multi select dropdown component.
+ Corrected formatting of locations in the Projects list.
+ Renamed _commaSeparatedDictValue for consistency.
+ Added Clusters and Locations to the Project Detail page
=> Project creation modal multiselect fields

django_api/django_api/apps/unicef/filters.py, polymer/src/elements/ip-reporting/progress-reports-filters.html
* Added backend filter for `report_type`
Added to work the same as `status` for consistency, though it should be noted that using something like this https://gist.github.com/maciej-jaworski/8ef66b4343acd6527a21359d24b916b1 would be way more elegant.
=> 473 Added filter for report_type

django_api/django_api/apps/core/validators.py, django_api/django_api/apps/indicator/models.py, django_api/django_api/apps/indicator/serializers.py, polymer/src/elements/cluster-reporting/indicator-editing-modal.html
Related to 
> Hitting “Save” button on the Edit indicator modal throws a backend error, hence none of the edit changes is applied:
> "Not valid data. Expected value is Cluster Objective, Cluster Activity, Partner Project, Partner Activity."
issue mentioned #480, the fix ended up big enough to warrant a separate branch IMO
* Fix serializer behaviour around updating reportable model
* Minor change related to backend changes
Original bug report mentioned an issue that I tracked down to invalid serialization of content type for reportable model. After that some more issues came up, all of which have been fixed.
Heads up on why all the `if validated_data.get('blueprint', {}).get` checks have been removed, per DRF docs
> Because the behavior of nested creates and updates can be ambiguous, and …
=> Fix issues around updating reportable from cluster UI

django_api/django_api/apps/indicator/models.py, django_api/django_api/apps/indicator/serializers.py, django_api/django_api/apps/indicator/views.py, django_api/django_api/apps/unicef/views.py, polymer/src/elements/indicator-details.html
* Django post_save signal to unlock Sent-back Cluster IndicatorReport's IndicatorLocationData instances
* Updates on PD Submit API and Cluster IndicatorReport Submit API to lock IndicatorLocationData instances
* IndicatorLocationDataUpdateAPIView to throw validation error on submitted IndicatorLocationData
* Hiding Enter Data button if the indicator location data is locked (TBD)
=> Feature - Locking submitted IndicatorLocationData [#651]

polymer/src/elements/disaggregations/disaggregation-table.html
Limited visibility of labels for quantity ('number') indicators in ip-reporting.
label.label is null in responses from backend. ( but the field exists )
=> limit visibility of labels for quantity indicators in ip-reporting

django_api/django_api/apps/indicator/serializers.py
* A validation check on a location data's indicator type to throw validation error on ratio type only.
=> Fix - X/0 validation logic only for Ratio type

polymer/src/elements/indicator-details.html, polymer/src/elements/reportable-meta.html
* None
* Change horizontal tabs of locations into vertical list
* Style list with consistent colors and have a fixed height for an individual report
* Make sure tab list and location page each have independent scrolling
=> [#1071] Location tabs vertical scrolling

polymer/src/elements/ip-reporting/pd-report-info.html
The Save button for the "Other Info" text fields was still being shown after the report had been submitted. I wrapped the button element in a `dom-if` so it will conditionally render as long as the report hasn't been submitted.
* Wrap save button element in a `dom-if` so it only renders if the report hasn't been submitted yet.
=> Hide save button after report has been submitted

django_api/django_api/apps/unicef/tests/test_models.py, django_api/django_api/apps/utils/emails.py, django_api/django_api/settings/base.py, django_api/requirements/base.txt
Added unicef_notifications library.
Attempting to handle the current email templates, con is that each time email sent templates are checked for changes and updates the notification record.
=> Add unicef_notifications to handle sending emails

django_api/django_api/apps/unicef/tests/test_models.py, django_api/django_api/apps/utils/emails.py, django_api/django_api/settings/base.py, django_api/requirements/base.txt
Django unit tests are failing due to dependency to redis. Either mock it or modify unit test cases to avoid this dependency.
=> Revert "Add unicef_notifications to handle sending emails"

django_api/django_api/apps/cluster/tests/test_views.py, django_api/django_api/apps/indicator/tests/test_views.py, django_api/django_api/apps/ocha/tests.py, django_api/django_api/apps/partner/tests/test_views.py, django_api/django_api/apps/unicef/tests/test_models.py, django_api/django_api/apps/unicef/tests/test_views.py
Update tests to mock the actual sending of emails, to prevent calls to redis
=> Update notification tests to mock email sending

polymer/src/elements/cluster-reporting/indicator-locations-modal.html, polymer/src/elements/cluster-reporting/indicator-locations-widget.html
If the user used the search functionality of the location dropdown, selected a location, then continued filling out the form, the onValueChanged event would fire again (because by selecting a location, the value would change from whatever search value the user put in back to an empty string), clearing out the user selection.
Also, there was an issue with the Locations button in Cluster Activity Indicator not working. This was because the locations array was now inside a `results` property in a larger object, so it was just a matter of changing `locations.find()` to `locations.results.find()`.
* Added a guard clause to simply not make an API call if the search string is empty
* Added an additional guard clause to make the API call once, in …
=> Fix location dropdown

react/id_management_frontend/package.json
Needed to update `webpack-dev-server` version to 3.1.11 to resolve security vulnerability.
* Updated `webpack-dev-server` from `package.json` to 3.1.11
=> fix: Update webpack-dev-server version to resolve security vulnerability

polymer/src/elements/ip-reporting/pd-report-info.html, polymer/src/elements/reportable-meta.html
* The character counters for the narrative assessment field and the three fields in the Other Info tab would only update when they became unfocused. I changed them to use Polymer's `paper-input` components with their built-in character counters, rather than use `input` elements with the `paper-input-char-counter` component.
=> [ch11490] Have input character counters update dynamically

polymer/src/elements/cluster-reporting/indicator-modal.html, polymer/src/elements/cluster-reporting/response-parameters/partners/activities/indicators.html, polymer/src/elements/cluster-reporting/response-parameters/partners/projects/indicators.html
* Added conditionally-rendered radio option for Adopt from Cluster Activity
* Added methods and observers for getting partner activities and cluster activity indicators
* Correctly build data object for adopted partner activity indicator and verify POST works for both custom and adopted partner activity indicators
=> [ch12052] Add "Adopt from Cluster Activity" option to Add Partner Activity Indicator modal

polymer/src/elements/reportable-meta.html, polymer/src/pages/app/ip-reporting/pd/pd-report.html
* Added conditional to manually set mode to "edit" if report was sent back to properly render Submit button
* Added a conditional to resolve an error that would occur when navigating away from a report. The report would try to auto-save its narrative assessment even if no changes had been made to the narrative assessment - the conditional should prevent it from autosaving when no changes have been made.
=> [ch12142] Fix submit button for report that was sent back

react/id_management_frontend/src/components/Users/UserRowExpanded.jsx
* When a user gets created in ID Management, there would be three options shown if the user has a role in the workspace: `edit`, `delete`, and `(make IP Admin)`. If they are made an IP Admin, that third option gets replaced with another `delete`, so there end up being two `delete` buttons. They both do the same thing (delete the user), so this fix should make it so that the first `delete` option is shown only if the user is not an IP Admin. If the user is an IP Admin, the first delete is hidden, and the second delete button is shown.
=> Show only one delete button for user in ID Management

polymer/src/elements/indicator-details.html, polymer/src/elements/reportable-meta.html, polymer/src/styles/app-theme-cluster.html, polymer/src/styles/app-theme-ip.html
The theme colors for the `Narrative assessment` Save button and the location list items had been hardcoded to follow the IP Reporting color scheme. This meant that when those components were being used in Cluster Reporting, they looked very out of place. This PR should fix that so the components actually use the correct color schemes depending on what app they're being used in.
* Added a new CSS variable for the paper-item color in the location list
* Deleted the hardcoded color values for the Edit/Save button for the narrative assessment so that it can use the appropriate color dynamically
=> Fix theme color in reports

polymer/src/elements/ip-reporting/report-attachments.html
There was a visual bug occurring when a user would upload multiple files with the same file name, but not the same extension. The UI on the attachments would get swapped somehow, showing the just-uploaded attachment with the exact same file extension as the existing one, even though upon refresh, it would display correctly. This PR should fix this.
* Tweaked existing conditional to also check the file extension along with the file name for duplicates
=> [ch12702] Fix issue with attachments' file extensions

polymer/src/elements/reportable-meta.html
* Added another conditional to check and see if user has actually clicked Edit on a narrative assessment field before saving it. This should prevent the `detached` method from checking all narrative fields and making PATCH API calls for each one, and now only make a PATCH for a narrative assessment whose corresponding Edit/Save button reads Save.
=> [ch12897] Prevent autosave for narrative assessment from running for all fields

polymer/src/elements/disaggregations/disaggregation-table-cell-number.html, polymer/src/elements/disaggregations/disaggregation-table-cell-percentage.html, polymer/src/elements/disaggregations/disaggregation-table-cell-ratio.html
Small bug I came across - a console error would pop up whenever opening an indicator report without any data values for a location.
* Added an extra conditional checking to make sure data is not undefined
=> Check if nullData is defined before setting values to null

polymer/src/elements/ip-reporting/ip-reporting-indicator-details.html, polymer/src/elements/ip-reporting/js/ip-reporting-indicator-details.js, polymer/test/unit/ip-reporting-indicator-details.test.js
* Moved externalized logic back into component to preserve `this` keyword context and have the data actually get set correctly. This function was one of the ones that couldn't live outside the component, but for some reason I moved it outside to a separate file anyway. Now that it's back in the component, the data should render correctly.
* Removed unnecessary unit tests now that function logic is no longer outside the component
=> [ch12716] Fix issue where report data in indicator detail slot is not rendering

polymer/src/elements/cluster-reporting/indicator-locations-modal.html, polymer/src/elements/disaggregations/disaggregation-table.html, polymer/src/elements/filters/status-filter/project-status-filter.html
fix: Resolve pathing issue in project-status-filter component and extra brackets highlighted by polymer lint
=> Polymer bundler error fix

django_api/django_api/apps/indicator/views.py, django_api/django_api/apps/unicef/views.py, polymer/src/elements/etools-prp-permissions.html, polymer/src/elements/reportable-meta.html
* Update several API views related to submitting Progress Reports to allow for user with IP Admin role to submit them
* Update `etools-prp-permissions` component to allow IP Admin role to submit progress reports
* Fix bugs related to localization conflicting with Progress Report overall status and narrative assessment save functionality
=> [ch12109] Allow IP Admin to submit reports

django_api/django_api/apps/indicator/views.py
* Added missing IP Admin permissions to IndicatorLocationDataUpdateAPIView class in `views.py`. It was working before because even though the user's IP permissions were IP Admin (and no other IP permissions), they still had Cluster Member permissions as well, which allowed them to enter data.
=> Add IP Admin permissions to IndicatorLocationDataUpdateAPIView [ch12109]

polymer/src/elements/etools-prp-progress-bar-alt.html, polymer/src/elements/etools-prp-progress-bar-cluster.html, polymer/src/elements/etools-prp-progress-bar.html, polymer/src/elements/list-view-single-indicator.html
* Had the `list-view-single-indicator` component pass down the `indicator.blueprint.display_type` property for each indicator down to the `etools-prp-progress-bar` component and its alternate versions
* Used the `displayType` prop to conditionally check if the number is already a percentage or not
=> [ch13530] Fix progress display for percentage indicator

polymer/src/elements/disaggregations/disaggregation-table-row.html
* Removed the localization that had been applied to the disaggregation labels in progress reports so that they can render properly
=> [ch13536] Remove localization from disaggregation labels

polymer/src/pages/app/ip-reporting/pd/pd-report-sr/reporting.html
* Make a new method in the SR `reporting.html` component that renders the correct SR description
* Method grabs the current progress report's `due_date`, finds the current programme document report, finds the correct SR `reporting_period` object inside the current programme document report's `reporting_periods` array, checks that the reporting period's `due_date` is before or equal to the current progress report's `due_date`, and checks to make sure the reporting period's `report_type` property is correct ('SR').
=> [ch13422] Correctly grab SR description

polymer/src/behaviors/utils.html
* Fixed the `_formatIndicatorValue` method to round down the percentage value and no longer multiply it by 100 (because it was already being converted earlier in the method)
=> [ch13530] Fix percentage display in Indicator details expanded view

polymer/src/locales.json
- Fixed translation for `enter_data` label to read "Saisir les données" rather than "Saisir la date"
=> [ch14330] Add correct translation for enter_data label

django_api/django_api/apps/unicef/exports/programme_documents.py, django_api/django_api/apps/unicef/exports/progress_reports.py, django_api/django_api/apps/unicef/exports/reportables.py, django_api/django_api/apps/unicef/models.py, django_api/django_api/apps/unicef/templates/report_annex_c_pdf.html, django_api/django_api/apps/unicef/templatetags/pdf_extras.py, django_api/django_api/apps/unicef/views.py
feat: Polished ratio value rendering in PDF export
+ funds_received_to_date_percentage to show 0 if percent value is None or -1
+ 2 decimal point rendering from funds_received_to_date_percentage in Annex-C PDF
+ 2 decimal point rendering from funds_received_to_date_percentage in ProgrammeDocument PDF export
+ 2 decimal point rendering from funds_received_to_date_percentage in ProgressReport List and Details PDF export
+ Ratio info formatting for target and baseline in Indicator list PDF export
+ new templatetag filter to percentize without scaling to 100% called percent_format
+ Used percent_format to render Reportable total correctly in Annex C PDF
=> PDF export rendering fix for ratio value in IP reporting

django_api/django_api/apps/indicator/serializers.py, django_api/django_api/apps/partner/serializers.py, polymer/src/elements/cluster-reporting/analysis/indicator-bucket.html, polymer/src/elements/cluster-reporting/analysis/operational-presence-map.html, polymer/src/redux/actions.html
- Added an observer method for getting the lat/long of a workspace and, if the map is empty, setting the map to center on the workspace.
- Added conditional logic to correctly render titles of indicator cards that were of type `partneractivityprojectcontext`
**Map**:
**Indicator card**:
=> Operational presence map fix and Cluster Indicator card fix

polymer/src/elements/cluster-reporting/add-response-plan-modal.html, polymer/src/elements/cluster-reporting/planned-action/activities/add-activity-from-project-modal.html, polymer/src/elements/cluster-reporting/planned-action/activities/add-existing-activity-from-project-modal.html, polymer/src/elements/cluster-reporting/planned-action/activities/creation-modal.html, polymer/src/elements/cluster-reporting/planned-action/activities/editing-modal.html, polymer/src/elements/cluster-reporting/planned-action/projects/creation-modal.html
- Replaced the default `paper-radio-group` component with a custom one for all applicable components
- The custom `paper-radio-group` component has no listeners attached to the arrow keys, so the arrow keys function as normal when typing text in a field under a radio button option.
- Cleaned up code and removed unused imports
=> [ch16546] Fix arrow keys from navigating radio buttons in certain modals

react/id_management_frontend/src/components/Users/AddPermissionsDialog.jsx, react/id_management_frontend/src/components/Users/renderPermissionsFields.jsx
- Added back vanilla clusterOptions (which had been modified in PR #1218 to account for clusters for partner) in order to fall back to in case partner wasn't applicable, like when creating an IMO user
- Cleaned up unnecessary code and console logs
=> [ch16602] Resolve issue with being unable to add a Cluster IMO user

react/id_management_frontend/src/components/Partners/PartnerDialog.jsx, react/id_management_frontend/src/components/form/SelectForm.jsx
- Added logic to enable/disable `cso_type` field depending on whether or not "CSO" was selected for the `partner_type` dropdown
- Added new state boolean to keep track of whether or not CSO field should be enabled or disabled
- Added logic to reset the boolean back to false upon closing the modal
=> [ch16984] Enable/disable CSO type field depending on Partner type value

polymer/src/behaviors/utils.html, polymer/src/elements/cluster-reporting/analysis/indicator-details.html
- Adjusted the `_toPercentage` method in `utils.html` to multiply and then divide by 100 in order to correctly return a percentage, rounded to the nearest hundredth.
=> [ch16896] Percentage indicator display bug fix

polymer/src/elements/cluster-reporting/creation-modal-project-details.html, polymer/src/elements/cluster-reporting/planned-action/projects/creation-modal.html, polymer/src/elements/cluster-reporting/project-details.html, polymer/src/elements/cluster-reporting/project-list-table.html
- Updated `paper-input` label in `creation-modal.html` component (the Add Project/Edit Project modals) with `"(USD)"` text at the end after the localized text
- Added `"(USD)"` text to the `project-details.html` component (the Project Details page), the `project-list-table.html` component (the expanding dropdown on the project list), and the `creation-modal-project-details.html` component (for when a user selects the "From OCHA" option and gets a project detail view in the modal
- Wrapped `total_budget` value in the `project-list-table.html` component with the `etools-prp-number.html` component in order to render 0 correctly when value is null
**Add Project modal**:
**Edit Project modal**:
**Project list table expanded view**:
**Add Project …
=> [ch16998] Update budget label to have "(USD)" text

polymer/src/elements/cluster-reporting/indicator-modal.html
- Added the missing `project_context_id` dropdown field for the custom activity indicator modal form in order to successfully create a custom activity indicator
=> [ch16946] Add project context dropdown field for adding a custom activity indicator

polymer/src/elements/cluster-reporting/planned-action/activities/add-existing-activity-from-project-modal.html
- Added `currentPartnerId` property to `add-existing-activity-from-project-modal.html` component
- Used the `currentPartnerId` value to return only the `filteredActivities` that belong to the current project's partner
=> [ch16924] Filter out partner activities that don't belong to the current project's partner

polymer/src/elements/cluster-reporting/indicator-editing-modal.html, polymer/src/elements/cluster-reporting/indicator-locations-widget.html
- Added `currentUserRoles` property to both the `indicator-editing-modal.html` and `indicator-locations-widget.html` components
- Added check inside the `_computeCanEditDetails` method to see if user's roles includes a `CLUSTER_IMO` role, and if so, to return true and allow the modal (and the baseline values for the locations) to be editable
=> [ch17011] Allow IMO users to edit partner activity indicators

polymer/src/elements/cluster-reporting/indicator-modal.html
- Removed the conditionals that would throw an error if a location's target value was greater than  the overall target value, for both percentage and ratio indicator types
=> [ch16906] Change validation for percentage/ratio indicator types

polymer_3/src_ts/pages/app/cluster-reporting/dashboard.ts
[ch19387] Cluster drop-down not displayed on IMO Dashboard
=> [ch19387] Cluster drop-down not displayed on IMO Dashboard

polymer_3/src_ts/elements/pull-modal.ts
[ch19671] IP-PRP: "Pull data" modal window has overlapping text
=> [ch19671] IP-PRP: "Pull data" modal window has overlapping text

polymer_3/src_ts/elements/labelled-item.ts
[ch20577] Fix overlapping text  in Partners Project Details
=> [ch20577] Fix overlapping text  in Partners Project Details

polymer_3/src_ts/pages/app/ip-reporting/pd/pd-report.ts
[ch20792] Clicking on the report header link redirects user to Overview (not showing PD details)
=> [ch20792] Clicking on the report header link redirects user to Overview (not showing PD details)

django_api/django_api/apps/unicef/serializers.py, django_api/django_api/apps/unicef/tests/test_views.py, django_api/django_api/apps/unicef/urls.py
[ch20968]
The incomplete var was checked against the constant `Boolean.True` which is set to the value `1`
But the value being passed in was `true`, this constant is used in a number of places, so doubt that this endpoint is the only one having an issue. Just fixed this endpoint for now.
=> Incomplete filter

django_api/django_api/apps/unicef/exports/annex_c_excel.py, django_api/django_api/apps/unicef/exports/programme_documents.py, django_api/django_api/apps/unicef/exports/reportables.py, django_api/django_api/apps/utils/mixins.py
[ch7973]
Filtering at the view level returns Reportables that match the filtering, but when we export the data all indicator reports are pulled for each of the Reportables, and so we're losing the filtering at this point.
=> Add filtering in exports at indicator reports level

django_api/django_api/apps/unicef/models.py, django_api/django_api/settings/base.py
[ch22076]
`PRP_FRONTEND_PMP_HOST` environment var needs to be set to relevant environments
=> Update notification link to unicef staff to point to pmp, not prp

django_api/etools_prp/apps/indicator/models.py
=> [ch26694] allow zero reports

.circleci/config.yml, frontend_cluster/.eslintrc.json, frontend_cluster/Dockerfile-bundle, frontend_cluster/Dockerfile-dev, frontend_cluster/package-lock.json, frontend_cluster/package.json, frontend_ip/.eslintrc.json, frontend_ip/Dockerfile-bundle, frontend_ip/Dockerfile-dev, frontend_ip/package-lock.json, frontend_ip/package.json
=> [ch27264]Update linting tools

.circleci/config.yml, frontend_ip/src_ts/elements/filters/dropdown-filter/dropdown-filter-multi.ts, frontend_ip/src_ts/elements/filters/location-filter-multi/location-filter-multi.ts
=> [ch30133]Fix empty locations dropdown

frontend_ip/src_ts/mixins/progress-report-utils-mixin.ts
[ch31346] Console error after visit multiple Reports and go back from browser
=> [ch31346] Console error after visit multiple Reports and go back from browser

django_api/etools_prp/apps/unicef/models.py, django_api/etools_prp/apps/unicef/serializers.py, django_api/etools_prp/apps/unicef/views.py
- added prefetch related to M2M fields
- adjusted serializers
_Why these changes :_ 
`Prefetch` 
ProgrammeDocument has 3 M2M fields : officer_programme_documents, unicef_focal_programme_documents and officer_programme_documents. Using prefetch avoid the N+1 query, making the whole thing faster. 
`select_related(None) `
In PRPLocationsManager.get_queryset, we have : 
**.select_related('parent').defer('geom', 'point')**
Adding  **select_related(None)** to ProgrammeDocument.locations_queryset clears that manager-level default, so the query doesn’t traverse parent, which is otherwise causing tests to fail
`.only('id', 'name', 'admin_level', 'admin_level_name', 'p_code')`
Similarly to how it’s done in **ShortLocationSerializer**, we only keep the columns we need, making the query faster. …
=> Optimised detail view for ProgramDocuments
