unicef/etools-partner-reporting-portal

- django_api/Dockerfile
- django_api/django_api/apps/core/management/commands/_privates.py
- django_api/django_api/settings/dev.py
- django_api/django_api/settings/staging.py
- django_api/django_api/urls.py
- django_api/django_api/uwsgi.ini
- django_api/requirements/base.txt
- docker-compose.yml
- nginx_proxy/nginx-site.conf.j2
This PR addresses a list of improvements for running Codefresh composition environment.
One noticeable change is to deprecate Django runserver in order to favor uWSGI dev server with python autoreload option. This would reload Django WSGI python module every 3 second, thus rendering any code changes in near real time.
There is a urlpattern fix for loading Django staticserve files at /api/static.
Codefresh composition now creates a set of fake data including Django superuser object so that Django admin access is available in Codefresh environment.
> Fix - Codefresh composition improvement

- django_api/django_api/apps/core/management/commands/_privates.py
- polymer/src/elements/disaggregations/table-content/two-disaggregations.html
- polymer/src/elements/ip-reporting/ip-reporting-indicator-details.html
* Correct rendering of fake data generation in terms of relationship between Indicator <-> IndicatorReport UI view
* Polymer table rendering logic improvements according to the data formats
> Fix - Disaggregation logic improvements

- django_api/django_api/apps/cluster/views.py
- django_api/django_api/apps/indicator/views.py
- django_api/django_api/apps/unicef/models.py
- django_api/django_api/apps/unicef/serializers.py
- django_api/django_api/apps/unicef/views.py
- django_api/django_api/settings/base.py
- django_api/requirements/base.txt
> Feature logger #100

- django_api/django_api/apps/indicator/serializers.py
* add report_status to returned data
> return indicator report status. #153

- django_api/Dockerfile
- django_api/django_api/apps/cluster/models.py
- django_api/django_api/apps/indicator/models.py
- django_api/django_api/apps/partner/models.py
- django_api/django_api/apps/unicef/models.py
- django_api/requirements/base.txt
- nginx_proxy/Dockerfile
* update django to 1.11 and dockers certs problems fix
> Feature django 1.11.x #44

- polymer/src/behaviors/routing.html
- polymer/src/elements/cluster-reporting/app-header.html
- polymer/src/elements/cluster-reporting/change-response-plan.html
- polymer/src/elements/cluster-reporting/nav.html
- polymer/src/pages/app/cluster-reporting.html
- polymer/src/pages/app/cluster-reporting/analysis.html
- polymer/src/pages/app/cluster-reporting/dashboard.html
- polymer/src/pages/app/cluster-reporting/planned-action.html
- polymer/src/pages/app/cluster-reporting/response-parameters.html
- polymer/src/pages/app/cluster-reporting/results.html
- polymer/src/styles/app-theme.html
+ Adding lefthand nav and routes
+ Adding variables for green colors
+ Adding the response plan (hardcoded for now) in the top nav and a response plan ID to the URL
> Scaffold frontend codebase for cluster reporting

- polymer/src/elements/ip-reporting/nav.html
- polymer/src/styles/page-nav.html
Use some icons to support readability of the left nav #149
> Added icons to the left navigation in IP Reporting

- db/codefresh_db.yml
- django_api/codefresh_django.yml
- nginx_proxy/codefresh_proxy.yml
- polymer/codefresh_polymer.yml
> added codefresh yaml files to get more flexible builds

- polymer/bower.json
- polymer/src/constants.html
- polymer/src/elements/cluster-reporting/cluster-report.html
- polymer/src/elements/cluster-reporting/project-details.html
- polymer/src/elements/disaggregations/disaggregation-table-cell.html
- polymer/src/elements/disaggregations/disaggregation-table-multi-cell.html
- polymer/src/elements/etools-prp-number.html
- polymer/src/elements/indicator-details.html
- polymer/src/elements/ip-reporting/ip-reporting-indicator-details.html
- polymer/src/elements/ip-reporting/partner-details.html
- polymer/src/elements/ip-reporting/pd-list.html
- polymer/src/elements/ip-reporting/pd-output.html
> Number formatting

- django_api/django_api/apps/core/common.py
- django_api/django_api/apps/indicator/views.py
- polymer/src/elements/cluster-reporting/cluster-report.html
- polymer/src/elements/error-modal.html
- polymer/src/pages/app/ip-reporting/pd/pd-report/submit.html
> Optional submission #259

- polymer/src/behaviors/date.html
This resolves #121 
* changed raw new Date to append UTC suffix when it's paired with moment.utc
Please check [this](https://stackoverflow.com/a/17856735) answer for explanation why raw new Date fails with moment.utc
> Fix for due date broken filter

- django_api/django_api/apps/indicator/views.py
- django_api/django_api/apps/unicef/views.py
> Fixed locations filter at indicator site

- django_api/django_api/apps/cluster/export.py
- django_api/django_api/apps/core/factories.py
- django_api/django_api/apps/core/management/commands/_privates.py
> Location admin refs #311

- polymer/src/pages/login.html
Added an option to submit form with 'enter'
Added an option for user to enter another email after submitting one already without refreshing a page.
Changed color for error text.
> Sign in magic link ip reporting permissions #337 #294

- django_api/django_api/apps/account/views.py
- django_api/django_api/apps/cluster/views.py
- django_api/django_api/apps/indicator/views.py
- django_api/django_api/settings/base.py
- django_api/django_api/urls.py
- django_api/requirements/base.txt
* django-rest-swagger API documentation generated
* Updated some APIView docstrings
> Feature api docs 354

- django_api/django_api/apps/unicef/serializers.py
> Fixed duplicate PDs error

- polymer/src/elements/cluster-reporting/indicator-modal.html
> Swap locations endpoint

- polymer/src/elements/cluster-reporting/cluster-report.html
- polymer/src/elements/ip-reporting/pd-output.html
- polymer/src/elements/list-view-indicators.html
- polymer/src/elements/list-view-single-indicator.html
> Calc methods

- polymer/index.html
- polymer/src/elements/page-title.html
- polymer/src/locales.json
- polymer/src/pages/app/cluster-reporting.html
- polymer/src/pages/app/ip-reporting.html
- polymer/src/pages/login.html
> Page title

- django_api/django_api/apps/unicef/filters.py
- polymer/src/elements/ip-reporting/nav.html
- changed default status filter:
- on programme document: active as default
- on reports: due, overdue and sent back as defaults
> changed default filter status

- polymer/src/elements/calculation-methods-demo-locations.html
- polymer/src/elements/calculation-methods-demo-modal.html
- polymer/src/elements/calculation-methods-demo-periods.html
- polymer/src/elements/calculation-methods-info-bar.html
- polymer/src/elements/ip-reporting/pd-details-calculation-methods.html
- new bar component with buttons to open demo modals
- shared demo modal
- separate components to display items in demo
> Added demo for indicators

- django_api/django_api/apps/core/permissions.py
- django_api/django_api/apps/core/tasks.py
- django_api/django_api/apps/unicef/serializers.py
- django_api/django_api/apps/unicef/views.py
- polymer/src/pages/app/ip-reporting/pd/pd-report.html
* Added checking PD status when submitting PR
> 459 pd reporting restrictions based on status

- polymer/src/elements/ip-reporting/pd-reports-list.html
- polymer/src/elements/ip-reporting/progress-reports-list.html
> Using correct component to display report title on list

- django_api/django_api/apps/partner/models.py
- django_api/django_api/apps/partner/serializers.py
- django_api/django_api/apps/partner/urls.py
- django_api/django_api/apps/partner/views.py
- polymer/src/elements/cluster-reporting/planned-action/activities/editing-modal.html
- polymer/src/endpoints.html
> Editing custom partner activity fails with 405 error
* Added endpoint for editing 
* Hooked up frontend to the new endpoint
> Added endpoint for updating PartnerActivity, updated frontend to use it

- polymer/src/behaviors/utils.html
- polymer/src/elements/etools-prp-auth.html
- polymer/src/elements/etools-prp-toolbar.html
@marcindo as per the discussion we had regarding toolbars.
> Don't 2-way bind redux-connected props

- polymer/src/elements/cluster-reporting/analysis/partner-reportable.html
- polymer/src/elements/ip-reporting/ip-reporting-indicator-details.html
- polymer/src/elements/list-placeholder.html
- changed placeholder element to support custom message
- added placeholder in analysis
- added placeholder to generic component that displays indicator reports
> 480 - Adding placeholder message for indicator report

- polymer/src/elements/cluster-reporting/analysis/partner-filters.html
- polymer/src/elements/cluster-reporting/cluster-report-filters.html
- polymer/src/elements/cluster-reporting/planned-action/activities/filters.html
- polymer/src/elements/cluster-reporting/planned-action/projects/filters.html
- polymer/src/elements/cluster-reporting/response-parameters/clusters/activities/contributing-partners-filters.html
- polymer/src/elements/cluster-reporting/response-parameters/clusters/activities/filters.html
- polymer/src/elements/cluster-reporting/response-parameters/clusters/objectives/filters.html
- polymer/src/elements/cluster-reporting/response-parameters/partners/activities/filters.html
- polymer/src/elements/cluster-reporting/response-parameters/partners/contacts/filters.html
- polymer/src/elements/cluster-reporting/response-parameters/partners/projects/filters.html
- polymer/src/elements/etools-prp-toolbar.html
- polymer/src/elements/filter-list.html
- polymer/src/elements/ip-reporting/indicators-filters.html
- polymer/src/elements/ip-reporting/pd-filters.html
- polymer/src/elements/ip-reporting/pd-report-filters.html
- polymer/src/elements/ip-reporting/progress-reports-filters.html
- polymer/src/elements/ip-reporting/report-filters.html
- polymer/src/styles/filter-styles.html
Added common component with basic padding styles to be used in all filters for consistency
> 502 change padding

- polymer/src/elements/report-status.html
- polymer/src/elements/reportable-meta.html
> 456 fix doc status

- polymer/src/elements/cluster-reporting/add-response-plan-modal.html
> 562 ocha import

- django_api/django_api/apps/ocha/imports/project.py
- django_api/django_api/apps/ocha/imports/serializers.py
- django_api/django_api/apps/ocha/imports/utilities.py
- django_api/django_api/apps/ocha/tasks.py
- django_api/django_api/settings/base.py
> fix import issues caused by schema changes

- polymer/src/pages/app.html
Plain notification visible after creating an account and logging in before receiving any permissions.
Remember to add a proper email address.
> 627 ad login splash screen

- polymer/src/elements/cluster-reporting/planned-action/projects/creation-modal.html
> Hide radios [#674]

- django_api/django_api/apps/indicator/serializers.py
- django_api/django_api/apps/indicator/urls.py
- django_api/django_api/apps/indicator/views.py
* A new Django API for returning reporting frequency info given Reportable IDs in POST
> Feature - Reporting frequency list API for PRP Indicators [#681]

- django_api/django_api/apps/cluster/import_indicators.py
- django_api/django_api/apps/cluster/serializers.py
- django_api/django_api/apps/cluster/views.py
- django_api/django_api/apps/core/permissions.py
- django_api/django_api/apps/indicator/views.py
- django_api/django_api/apps/partner/views.py
- django_api/django_api/apps/unicef/views.py
- django_api/django_api/apps/utils/mixins.py
* Adjusting Backend API permission classes for all Django apps
> Feature - API permission enforcement [#725]

- django_api/django_api/apps/core/tasks.py
* Report generator celery task update to create additional HR progress report for each cluster indicator
* Some code refactoring
> Feature - report generator hr pr update [#737]

- django_api/django_api/apps/core/tasks.py
- django_api/django_api/apps/indicator/serializers.py
* Report generator task update to keep track of Indicator report instances for UNICEF non-cluster HR progress report in order to delete empty HR Progress report
* Updated IndicatorReportSerializer's indicator_location_data field to exclude Cluster only location data for IP reporting 
> Feature - Report generator hr pr update #737

- polymer/src/elements/cluster-reporting/planned-action/projects/creation-modal.html
> remove doubled error box in creation modal

- django_api/django_api/apps/core/helpers.py
- django_api/django_api/apps/core/tasks.py
- django_api/django_api/apps/indicator/serializers.py
- Report generator logic fix for weekly period
- Report generator logic fix for preventing pro-rata monthly reporting periods
- Report generator logic fix for custom dates with requiring start_date_of_reporting_period
- Serializer validations to prevent start date of reporting period in custom due dates
> Fix - report generator for periods #814 #798 #789

- polymer/src/elements/cluster-reporting/planned-action/projects/creation-modal.html
> hide partner in project creation modal edit mode

- polymer/src/elements/filter-list.html
> substract number of ignored filters from ready count

- django_api/django_api/apps/cluster/export_indicators.py
> Excel import/export fixes

- django_api/django_api/apps/indicator/models.py
- django_api/django_api/apps/unicef/models.py
> 874 pdf export error

- polymer/src/elements/confirm-box.html
> Add exclamation mark to modal, bold text

- django_api/django_api/apps/unicef/filters.py
- django_api/django_api/apps/unicef/views.py
> Unicef indicator filters

- polymer/src/elements/cluster-reporting/chip-disagg-value.html
> #912 Change chip-disagg-value maxlength to 128

- polymer/src/elements/ip-reporting/pd-output.html
- polymer/src/elements/ip-reporting/pd-report-info.html
- polymer/src/pages/app/ip-reporting/pd/pd-report-sr/reporting.html
- polymer/src/pages/app/ip-reporting/pd/pd-sent-back.html
> 947 fix sent back report permissions

- django_api/django_api/apps/unicef/exports/annex_c_excel.py
> Fixed Indicator Target Percentage in IP portal

- polymer/src/elements/disaggregations/disaggregation-table-cell-number.html
> Display '-' if no location data is present

- polymer/src/behaviors/notifications.html
- polymer/src/elements/indicator-details.html
- polymer/src/elements/ip-reporting/pd-output.html
- polymer/src/elements/pull-modal.html
- polymer/src/pages/app.html
On API error toast with its message will be shown.
> 980 error message pull data from hr

- polymer/src/behaviors/utils.html
- polymer/src/elements/cluster-reporting/cluster-report.html
- polymer/src/elements/indicator-details.html
- polymer/src/elements/ip-reporting/pd-output.html
> 973 calculation methods for ratio and percentage indicators

- django_api/django_api/apps/cluster/export_indicators.py
> Modified Total value in export from 0 to empty cell

- django_api/django_api/apps/indicator/models.py
- django_api/django_api/apps/unicef/models.py
- django_api/django_api/apps/unicef/tasks.py
- django_api/django_api/templates/emails/on_indicator_report_status_change_sent_back.html
- django_api/django_api/templates/emails/on_indicator_report_status_change_sent_back_cluster.html
- django_api/django_api/templates/emails/on_indicator_report_status_change_subject.txt
- django_api/django_api/templates/emails/on_progress_report_status_change_accepted.html
- django_api/django_api/templates/emails/on_progress_report_status_change_sent_back.html
- django_api/django_api/templates/emails/on_progress_report_status_change_subject.txt
> 276 email notifications from prp

- polymer/src/elements/cluster-reporting/dashboard/constrained-reports-list.html
- polymer/src/elements/page-body.html
- react/id_management_frontend/Dockerfile-bundle
> Develop -> Master

- django_api/django_api/apps/core/api.py
- django_api/django_api/apps/core/mixins.py
- django_api/django_api/settings/base.py
Changes needed for password reset support.
With this change the user is able to change passwords but currently the redirect does not get handled properly so the user does not get logged in after password reset. I added a TODO in there to look into it more.
> Reset password

- polymer/src/elements/ip-reporting/pd-report-export-button.html
* None
* Updated text for Download button from `Download Annex C Part A` to `Download report in standard template format`.
> fix: Changed button text to proper name [#1070]

- polymer/src/pages/unauthorized.html
* None
* Changed error message for logged-in users without a PRP role to display proper text.
> 1072 - Updated error message for logged-in users without PRP role

- polymer/src/elements/disaggregations/disaggregation-field.html
* None
* Added `ready` function to check for field validation on opening modal.
> [#1069] Have form validate on modal open for blank entries

- django_api/requirements/base.txt
* fix: Removed flower pypi package as broken dependency to celery beat command and also as unused dependency
> Develop -> Master 20190309 (Hot fix)

- polymer/src/elements/disaggregations/disaggregation-table.html
* fix: Added total calcullation handling for zero disaggregated data on _fieldValueChanged method for disaggregation-table
+ Re-assignment of totals from component to local copy before re-updating component totals copy
> Develop -> Master 20190312 (Hot fix)

- django_api/django_api/apps/unicef/serializers.py
- polymer/src/elements/ip-reporting/pd-report-info.html
- polymer/src/elements/reportable-meta.html
* Change backend character limit from 255 to 2000 chars.
* Add Edit/Save toggle button for narrative fields
> [#1086] Saving narratives

- django_api/django_api/apps/core/mixins.py
- django_api/django_api/settings/base.py
* Added string strip method after lowercasing email address from AD response
* Disabled create_user pipeline function so that the user won't be created if not exist
> [#1078] [#1077] User email handling at AD response

- django_api/django_api/apps/core/factories.py
- django_api/django_api/apps/indicator/tasks.py
- django_api/django_api/apps/unicef/models.py
- django_api/django_api/apps/unicef/tests/test_models.py
- django_api/django_api/apps/utils/emails.py
- django_api/django_api/templates/emails/due_progress_report.html
- django_api/django_api/templates/emails/due_progress_report_subject.txt
- django_api/django_api/templates/emails/on_progress_report_status_change_accepted.html
- django_api/django_api/templates/emails/on_progress_report_status_change_sent_back.html
- django_api/django_api/templates/emails/on_progress_report_status_change_subject.txt
- django_api/django_api/templates/emails/on_progress_report_status_change_submitted.html
- django_api/django_api/templates/emails/overdue_progress_report.html
- django_api/django_api/templates/emails/overdue_progress_report_subject.txt
* Email notifications for due progress reports in a week daily basis
* Email notifications for overdue progress reports weekly basis
> [#1074] [#1075] report email notifications

- polymer/src/elements/etools-prp-ajax.html
- polymer/src/elements/etools-prp-progress-bar.html
- polymer/src/elements/ip-reporting/pd-report-info.html
- polymer/src/elements/ip-reporting/report-attachments.html
* None
* Add spinner when file upload is in progress in the "Other Info" tab of a report.
* Add styling to have spinner appear only on one side of each attachment field.
> [#1073] File upload indicator

- polymer/src/elements/ip-reporting/pd-report-info.html
* Fixed a typo to make the conditional rendering for the Save button work properly
> [ch11492] Render save button correctly

- polymer/src/elements/ip-reporting/js/pd-report-info.js
- polymer/src/elements/ip-reporting/pd-report-info.html
* Simplified logic for grabbing input fields
* Added debounce around thunk - there should no longer be multiple cancelled API calls
> [ch11398] Simplify logic for saving Other Info text fields

- polymer/src/elements/disaggregations/disaggregation-table.html
* Removed the DOM template input field for specifying percentage
* Hardcoded percentage value to always be 1
> [ch10760] Remove % Assignment for Dual Reporting

- polymer/src/elements/cluster-reporting/indicator-modal.html
* Added dom-if conditional to check if parter ID exists in Redux store. If so, the radio buttons will render, but if not, only the custom form will render.
> [ch12038] Remove Adopt Cluster Objective option as Cluster IMO

- django_api/django_api/apps/partner/models.py
* fix: Use m2m_changed model signal instead [ch10757] + Grab locations from pk_set to get or create ReportableLocationGoal for  all reportables
> Fix - Edit Location set [ch10757]

- polymer/src/elements/cluster-reporting/indicator-modal.html
* Added dropdown for partner selection in Project Indicator modal if user is Cluster IMO
* Added observers to save partner selection and enable cluster dropdown
* Added dom-if template to check if user is Cluster IMO or not to conditionally render Partner dropdown
* Tweaked existing conditionals to better determine user role and render correct modal form
* Added method for fetching list of partners belonging to cluster
> [ch12043] Render partner selection dropdown for Add Project Indicator modal

- polymer/src/elements/cluster-reporting/indicator-modal.html
- polymer/src/elements/cluster-reporting/response-parameters/partners/projects/indicators.html
* Removed partner dropdown from Add Project Indicator modal
* Set indicator component to pass down partner project data and set partner ID in indicator modal using this partner project data
> [ch12043] Remove partner dropdown

- django_api/django_api/apps/ocha/imports/project.py
- django_api/django_api/apps/ocha/imports/serializers.py
- django_api/django_api/apps/ocha/imports/utilities.py
- django_api/django_api/apps/ocha/tasks.py
- django_api/django_api/apps/ocha/views.py
- django_api/django_api/apps/partner/models.py
- polymer/src/elements/cluster-reporting/creation-modal-project-details.html
- OCHA API logic fixes
- Location handlings
- OCHA indicators as project indicators
- Partner Activity auto-adoption for Cluster Activity in Project
- Location addition for project and adopted partner activity from project indicator
- List of indicator UI in ADD PROJECT modal UI
> OCHA Partner Project Import [ch10765]

- polymer/src/elements/cluster-reporting/indicator-modal.html
* Removed radio button options and immediately render custom indicator form for Add Activity Indicator modal if user is IMO
> [ch12052] Show custom indicator form instead of radio options for Add Activity Indicator

- polymer/src/elements/cluster-reporting/indicator-locations-widget.html
- polymer/src/elements/cluster-reporting/planned-action/projects/creation-modal.html
- polymer/src/elements/filters/dropdown-filter/dropdown-filter-multi.html
* Added conditional to `dropdown-filter-multi` component to fire filterReady method if no locations are available
> [ch12575] Fix PD filter from infinitely loading

- react/id_management_frontend/src/components/Users/EditPermissionDialog.jsx
* Changed one line to a longer conditional to catch if ownProps.user is null to resolve the issue of activate/deactivate not working and the issue of the "Make IP Admin" button not working
> [ch11197] Fix ID Management bugs with activation and roles

- polymer/src/elements/ip-reporting/pd-details-overview.html
* Added amendment types dictionary to loop through amendment types and render them in a human-readable format on the frontend
> [ch12651] Show amendment types in human-readable format

- django_api/django_api/apps/unicef/templates/progress_report_detail_pdf_export.html
- django_api/django_api/apps/unicef/templates/progress_report_list_pdf_export.html
- django_api/django_api/apps/unicef/views.py
* fix: Corrected PR instance attachment check to use attachments.exists ORM
+ ProgressReportSRSubmitAPIView[ch11241]
+ ProgressReport list & detail PDF export
> [ch11241] SR Progress Report submission bug fix

- polymer/index.html
- polymer/src/behaviors/analysis-chart.html
- polymer/src/elements/cluster-reporting/analysis/operational-presence-map.html
- polymer/src/pages/app/cluster-reporting/dashboard.html
* Take out browser-sniffing conditional logic for web-components v0
* Clean up various bugs related to `manifest.json` and Zendesk support widget
* Remove `shadowRoot` and just use `this`
> [ch12867] Change entry point to account for web-components v0 deprecation

- django_api/django_api/apps/indicator/serializers.py
- polymer/src/elements/indicator-details.html
* Added `is_hf_indicator` field to `IndicatorReportListSerializer`
* Added method for checking if `is_hf_indicator` property on `disaggregations` object is truthy, and if so, render the option to pull data from HR
> [ch12700] Conditionally render "Pull Data from HR" option on indicator reports

- polymer/src/elements/ip-reporting/progress-reports-toolbar.html
* Added PDF export button and corresponding URL to `progress-reports-toolbar component`
> [ch11167] Add PDF export button to Progress Reports page

- polymer/src/pages/unauthorized.html
* Added sign-out button to Unauthorized page
* Added styling to sign-out button and layout
> [ch10776] Add Sign Out button to Unauthorized page

- django_api/django_api/apps/unicef/views.py
This PR completes [ch12656]
- refactor: Use IndicatorReport's is_complete property [ch12656]
+ Deleted a previous for-loop since ratio type can have denominator value of 0
> IP Progress Report submit API fix [ch12656]

- django_api/django_api/apps/unicef/views.py
- feat: Allowed IP_VIEWER permission to Annex C [ch12724]
> Annex C PDF report for IP Viewer role [ch12724]

- polymer/src/elements/ip-reporting/js/pd-output-list-toolbar.js
- polymer/src/elements/ip-reporting/pd-output-list-toolbar.html
* Added method for computing whether user is IP Admin or IP Viewer, and if so, hide the Refresh button
> [ch12855] Hide Refresh button depending on user role

- django_api/django_api/apps/unicef/exports/progress_reports.py
- django_api/django_api/apps/unicef/templates/fragments/programme_information.html
- django_api/django_api/apps/unicef/templates/progress_report_detail_pdf_export.html
- django_api/django_api/apps/unicef/templatetags/pdf_extras.py
- PDF template file changes
- Restructuring table sections
- Adding a new section
> [ch11189] Progress report summary PDF export fix

- polymer/gulpfile.js
* Add root `/` to fallbackWhitelist array in `gulpfile.js`
> [ch13308] Fix redirect to not-found page for unknown pages

- docker-compose.polymer-bundle.yml
- polymer/Dockerfile-bundle
- polymer/gulpfile.js
- polymer/index.html
* Made appShellImport link be asynchronous to try and see if redirect issue would get resolved
* Updated docker-compose polymer-bundle and Dockerfile-bundle files with necessary changes to have them run
> [ch13308] Try and resolve redirect issues to not-found page

- polymer/src/elements/ip-reporting/report-attachments.html
- polymer/src/pages/app.html
* Adjusted regex to whitelist alphanumeric characters and replace all other characters with an underscore
> [ch11495] Add more comprehensive regex for file upload names

- react/id_management_frontend/src/components/Users/UserRowStatus.jsx
* Added new `aoRole` variable to evaluate whether specific user had an Authorized Officer role, and if so, whether it was inactive
* Expanded original conditional evaluating user status to `Inactive` to include whether `aoRole` was truthy
> Check if user has AO role that is inactive [c13526]

- django_api/django_api/apps/unicef/exports/progress_reports.py
- Calculation method to reflect across locations in ProgressReport details PDF export
> refactor: Rename a field in ProgressReport PDF [ch13325]

- django_api/django_api/apps/unicef/templates/report_annex_c_pdf.html
- fix: Use Reportable total on cumulative progress column on Annex C PDF HTML
> [ch13340] Annex C PDF cumulative progress column fix

- polymer/gulpfile.js
- polymer/src/app-shell.html
- polymer/src/behaviors/utils.html
* Change `navigateFallback` value in `gulpfile.js` to just `/` rather than `/index.html`, which may have been the cause of the issue...we'll see!
> [ch13308] Redirect not properly working for non-existent pages

- polymer/src/app-shell.html
- polymer/src/behaviors/utils.html
* Removed template and added conditional to pageChanged method to catch invalid pages
* Cleaned up unused utils method
> [ch13308] Redirect to not-found page correctly

- docker-compose.polymer-bundle.yml
- polymer/Dockerfile-bundle
- polymer/src/app-shell.html
* Moved page validation into `_routePageChanged` method
> [ch13308] Fix redirect to "Not Found" page

- django_api/django_api/apps/unicef/serializers.py
- refactor: Convert all PersonSerializer fields to SerializerMethodField in unicef [ch13503]
+ Pass-in queryset filter method on active=True only
> Queryset filter on PD PersonSerializer fields [ch13503]

- django_api/django_api/apps/unicef/templates/progress_report_detail_pdf_export.html
- refactor: Iterate attachments in PDF export HTML template [ch13514]
+ Display file.name with br tag
> [ch13514] ProgressReport attachment info display in Detail PDF export

- django_api/django_api/apps/unicef/views.py
- feat: Added ProgressReport instance validation from filename tokens [ch13608]
> [ch13608] Progress report instance import validation from filename

- django_api/django_api/apps/unicef/exports/programme_documents.py
- django_api/django_api/apps/unicef/templatetags/pdf_extras.py
- django_api/django_api/apps/unicef/views.py
- refactor: Add .filter(active=True) on Person model queries [ch13509]
+ ProgressReport submit APIs
+ PD XLSX export
+ ProgressReport programme information fragments
> [ch13509] Active Authorized Officer and Partner focal point information on exports

- django_api/django_api/apps/ocha/imports/project.py
- django_api/django_api/apps/ocha/imports/response_plan.py
- django_api/django_api/apps/ocha/imports/serializers.py
- django_api/django_api/apps/ocha/imports/utilities.py
- django_api/django_api/apps/ocha/tasks.py
- django_api/django_api/apps/ocha/utilities.py
- django_api/django_api/apps/ocha/views.py
- OCHA import API regression fixes from Response Plan to Partner Project Import
- PartnerActivity adoption from imported OCHA ClusterActivity with ProjectContext
> [ch10765] OCHA API regression fix

- polymer/src/elements/etools-prp-progress-bar.html
- polymer/src/elements/ip-reporting/pd-details-overview.html
- polymer/src/elements/ip-reporting/pd-modal.html
- Added a method to calculate funds value and return the number or N/A if null or -1
- Added value to both `pd-details-overview` and `pd-modal` components
> [ch13502] Render disbursement info in the UI

- polymer/src/app-shell.html
- Add function to `app-shell.html` to set `location.pathname` to `'/landing'`
> [ch14714] Redirect to landing page

- django_api/django_api/templates/emails/on_create_user.html
- django_api/django_api/templates/emails/on_role_assign_change.html
* Updated body text in `on_create_user.html` and `on_role_assign_change.html` to the provided text
> [ch14892] [ch14893] Change the text for notification emails

- django_api/django_api/apps/indicator/models.py
- feat: Added conditional ORM query for QPR Progress report reportable [ch15204]
> [ch15204] Indicator report aggregation change for Progress Report

- django_api/django_api/apps/indicator/serializers.py
- django_api/django_api/apps/partner/filters.py
- PartnerProject filter class fix
- Validation fix for start_date_of_reporting_period in create/update for PartnerActivity
> Cluster indicator create/update fixes

- django_api/django_api/apps/indicator/utilities.py
- django_api/django_api/apps/unicef/exports/progress_reports.py
- django_api/django_api/apps/unicef/exports/reportables.py
- django_api/django_api/apps/unicef/templates/report_annex_c_pdf.html
refactor: value formatting fix in PDF exporting [ch15186]
+ format_total_value_to_string method update to handle DivisionByZero exception and explicit ratio display type handling
+ Updated PDF exporters for progress report detail and list
+ ReportableListtPDFExporter
+ Annex-C PDF HTML template to handle ratio display type explicitly
> [ch15186] ProgressReport PDF export fix for value formatting

- django_api/django_api/apps/unicef/tasks.py
fix: Added logic to reactivate Person after syncing [ch15247]
+ UNICEF focal point
+ Partner focal point
+ Authorized officer
> [ch15247] PD sync fix for Person activation

- django_api/django_api/apps/indicator/serializers.py
- polymer/src/elements/cluster-reporting/analysis/indicator-bucket.html
- polymer/src/elements/cluster-reporting/analysis/indicators.html
- polymer/src/elements/etools-prp-progress-bar.html
- Serializer changes for total progresses
- percentage bar UI component to format incoming value correctly
> [ch15580] progress against target is not working on

- django_api/django_api/apps/cluster/serializers.py
- django_api/django_api/apps/cluster/views.py
- django_api/django_api/apps/id_management/urls.py
- react/id_management_frontend/src/actions.js
- react/id_management_frontend/src/components/Partners/Partners.jsx
- react/id_management_frontend/src/components/Users/AddPermissionsDialog.jsx
- react/id_management_frontend/src/components/Users/renderPermissionsFields.jsx
- react/id_management_frontend/src/fetch.js
- react/id_management_frontend/src/helpers/props.js
- react/id_management_frontend/src/reducers/clustersForPartner.js
- react/id_management_frontend/src/reducers/partners.js
- react/id_management_frontend/src/reducers/reducers.js
- react/id_management_frontend/src/store.js
- New API endpoint for cluster list on partner ID
- Serializer changes
- Redux changes to call clusters given partner ID instead of current user's cluster list
> [ch15560] load priority for newly added partners

- react/id_management_frontend/src/components/Partners/PartnerDialog.jsx
- react/id_management_frontend/src/components/Partners/partnerLabels.js
- Removed unnecessary labels "Total CT CP", "Total CT CY", "Risk Rating", and "Basis for Risk Rating"
- Updated "Vendor number" field label to read "UNICEF vendor number"
> [ch15558] Updated Add Partner form in ID Management

- polymer/bower.json
- polymer/src/app-shell.html
> Adds etools-piwik-analytics component to track app analytics

- django_api/django_api/apps/indicator/serializers.py
- polymer/src/elements/cluster-reporting/indicator-editing-modal.html
- polymer/src/elements/cluster-reporting/indicator-locations-widget.html
- polymer/src/elements/cluster-reporting/indicator-modal.html
- polymer/src/elements/cluster-reporting/planned-action/activities/add-existing-activity-from-project-modal.html
- polymer/src/elements/cluster-reporting/response-parameters/clusters/objectives/indicators.html
- polymer/src/elements/cluster-reporting/response-parameters/partners/projects/activities.html
- polymer/src/elements/list-view-indicators.html
- polymer/src/pages/app/cluster-reporting/response-parameters/clusters/objective.html
- ClusterIndicatorSerializer changes on updating partner activity indicator
- Polymer frontend validation logic changes on locatiion widget and target & baseline
> [ch15975] cluster indicator regressions

- react/id_management_frontend/src/helpers/validation.js
- Adjusted the regex validation to include 0 in the phone number field
> [ch16543] Tweak phone number validation

- react/id_management_frontend/src/components/Users/renderPermissionsFields.jsx
- Make conditional for rendering `SearchSelectForm` more explicit to prevent multiple `SearchSelectForms` from rendering
- Added check for `user_type` in first conditional (for creating a Partner user) and added a check for an empty `clusterForPartnerOptions` in the second conditional (for creating IMO user as Cluster System Admin)
> [ch16717] Fix duplicate field showing when adding a user in ID Management

- polymer/bower.json
- polymer/src/app-shell.html
> Updates piwik tracker and fixes page recording

- react/id_management_frontend/src/components/layout/MainBackButton.jsx
- Removed an invalid part of the redirect URL text in the `MainBackButton.jsx` component
> [ch16988] Properly redirect from ID Management

- polymer/bower.json
> Updates matomo tracker to allow testing in prp dev

- polymer/src/elements/cluster-reporting/indicator-editing-modal.html
- polymer/src/elements/cluster-reporting/indicator-locations-widget.html
Reverts unicef/etools-partner-reporting-portal#1239
- Reverting this PR to handle permission better compared to just if-else statements
> Revert "[ch17011] Allow IMO users to edit partner activity indicators"

- polymer/src/elements/cluster-reporting/indicator-editing-modal.html
- polymer/src/elements/cluster-reporting/indicator-locations-widget.html
- fix: Removed isPAI check against IMO role on editing indicator modal [ch17011]
> [ch17011] Rebuilt PR - PAI edit permission for IMO on both cluster and partner activity indicator

- polymer/bower.json
> Reverts etools-piwik-analytics to 1.0.11

- polymer_3/src_ts/utils/fire-custom-event.ts
Added fireEvent in utils folder
> Added fireEvent in utils folder

- polymer_3/src_ts/elements/app-redirect.ts
- polymer_3/src_ts/elements/calculation-method.ts
- polymer_3/src_ts/elements/etools-prp-ajax.ts
- polymer_3/src_ts/elements/filter-list.ts
- polymer_3/src_ts/elements/frequency-of-reporting.ts
- polymer_3/src_ts/elements/indicator-details.ts
- polymer_3/src_ts/elements/json-field.ts
- polymer_3/src_ts/elements/list-paginator.ts
- polymer_3/src_ts/elements/pull-modal.ts
- polymer_3/src_ts/elements/refresh-report-modal.ts
- polymer_3/src_ts/elements/reportable-meta.ts
- polymer_3/src_ts/endpoints.ts
- polymer_3/src_ts/mixins/modal-mixin.ts
- polymer_3/src_ts/mixins/notifications-mixin.ts
- polymer_3/src_ts/mixins/page-nav-mixin.ts
- polymer_3/src_ts/mixins/pagination-mixin.ts
- polymer_3/src_ts/mixins/routing-mixin.ts
[ch18187] Polymer3 Common elements migration
> [ch18187] Polymer3 Common elements migration

- polymer_3/src_ts/elements/form-fields/cluster-dropdown-content.ts
- polymer_3/src_ts/elements/form-fields/cluster-dropdown-input.ts
- polymer_3/src_ts/elements/form-fields/cluster-location-content.ts
- polymer_3/src_ts/elements/form-fields/dropdown-form-input.ts
- polymer_3/src_ts/elements/form-fields/partner-dropdown-content.ts
[ch18267] Form-fields folder migration to Polymer3
> [ch18267] Form-fields folder migration to Polymer3

- polymer/src/behaviors/utils.html
- polymer/src/elements/app-switcher.html
- polymer/src/elements/calculation-methods-demo-modal.html
- polymer/src/elements/cluster-reporting/add-response-plan-modal.html
- polymer/src/elements/cluster-reporting/analysis/indicator-bucket.html
- polymer/src/elements/cluster-reporting/disaggregations-dropdown-widget.html
- polymer/src/elements/cluster-reporting/indicator-editing-modal.html
- polymer/src/elements/cluster-reporting/indicator-locations-modal.html
- polymer/src/elements/cluster-reporting/indicator-locations-widget.html
- polymer/src/elements/cluster-reporting/indicator-modal.html
- polymer/src/elements/cluster-reporting/message-imo-modal.html
- polymer/src/elements/cluster-reporting/planned-action/activities/add-activity-from-project-modal.html
- polymer/src/elements/cluster-reporting/planned-action/activities/add-existing-activity-from-project-modal.html
- polymer/src/elements/cluster-reporting/planned-action/activities/creation-modal.html
- polymer/src/elements/cluster-reporting/planned-action/activities/editing-modal.html
- polymer/src/elements/cluster-reporting/planned-action/projects/creation-modal.html
- polymer/src/elements/cluster-reporting/planned-action/projects/editing-modal.html
- polymer/src/elements/cluster-reporting/response-parameters/clusters/activities/creation-modal.html
- polymer/src/elements/cluster-reporting/response-parameters/clusters/activities/editing-modal.html
- polymer/src/elements/cluster-reporting/response-parameters/clusters/objectives/creation-modal.html
- polymer/src/elements/cluster-reporting/response-parameters/clusters/objectives/editing-modal.html
- polymer/src/elements/etools-prp-chips.html
- polymer/src/elements/ip-reporting/authorized-officer-modal.html
- polymer/src/elements/ip-reporting/pd-details-calculation-methods.html
- polymer/src/elements/list-view-single-indicator.html
[ch18311] There is a cluster problem
> [ch18311] There is a cluster problem

- polymer_3/src_ts/elements/ip-reporting/js/authorized-officer-modal-functions.ts
- polymer_3/src_ts/elements/ip-reporting/js/indicators-toolbar-functions.ts
- polymer_3/src_ts/elements/ip-reporting/js/ip-reporting-indicator-details-functions.ts
- polymer_3/src_ts/elements/ip-reporting/js/partner-details-functions.ts
- polymer_3/src_ts/elements/ip-reporting/js/pd-details-calculation-methods-functions.ts
- polymer_3/src_ts/elements/ip-reporting/js/pd-details-doc-download-functions.ts
- polymer_3/src_ts/elements/ip-reporting/js/pd-details-overview-functions.ts
- polymer_3/src_ts/elements/ip-reporting/js/pd-details-reporting-requirements-functions.ts
- polymer_3/src_ts/elements/ip-reporting/js/pd-details-reports-functions.ts
- polymer_3/src_ts/elements/ip-reporting/js/pd-list-toolbar-functions.ts
- polymer_3/src_ts/elements/ip-reporting/js/pd-output-functions.ts
- polymer_3/src_ts/elements/ip-reporting/js/pd-output-list-functions.ts
- polymer_3/src_ts/elements/ip-reporting/js/pd-output-list-toolbar-functions.ts
- polymer_3/src_ts/elements/ip-reporting/js/pd-report-info-functions.ts
- polymer_3/src_ts/elements/ip-reporting/js/pd-reports-list-functions.ts
- polymer_3/src_ts/elements/ip-reporting/js/pd-reports-report-title-functions.ts
- polymer_3/src_ts/elements/ip-reporting/js/pd-reports-toolbar-functions.ts
- polymer_3/src_ts/elements/ip-reporting/js/progress-reports-list-functions.ts
- polymer_3/src_ts/elements/ip-reporting/js/progress-reports-toolbar-functions.ts
- polymer_3/src_ts/elements/ip-reporting/js/report-attachments-functions.ts
[ch18350] Migrate ip-reporting/js folder to Polymer3
> [ch18350] Migrate ip-reporting/js folder to Polymer3

- polymer_3/src_ts/elements/disaggregations/disaggregation-field.ts
- polymer_3/src_ts/elements/disaggregations/disaggregation-modal.ts
migrated disaggregation field and modal
> migrated disaggregation field and modal

- polymer_3/src_ts/elements/ip-reporting/pd-reports-toolbar.ts
- polymer_3/src_ts/elements/ip-reporting/progress-reports-filters.ts
- polymer_3/src_ts/elements/ip-reporting/progress-reports-list.ts
- polymer_3/src_ts/elements/ip-reporting/progress-reports-toolbar.ts
- polymer_3/src_ts/elements/ip-reporting/report-attachments.ts
- polymer_3/src_ts/elements/ip-reporting/report-filters.ts
- polymer_3/src_ts/elements/ip-reporting/risk-rating.ts
> ip-reporting-migration

- polymer_3/src_ts/elements/form-fields/cluster-dropdown-content.ts
- polymer_3/src_ts/elements/form-fields/cluster-dropdown-input.ts
- polymer_3/src_ts/elements/form-fields/cluster-location-content.ts
- polymer_3/src_ts/elements/form-fields/dropdown-form-input.ts
- polymer_3/src_ts/elements/form-fields/partner-dropdown-content.ts
- polymer_3/src_ts/elements/indicator-details.ts
- polymer_3/src_ts/elements/ip-reporting/pd-filters.ts
- polymer_3/src_ts/elements/ip-reporting/pd-list-toolbar.ts
- polymer_3/src_ts/elements/ip-reporting/pd-list.ts
- polymer_3/src_ts/elements/ip-reporting/pd-modal.ts
- polymer_3/src_ts/elements/ip-reporting/pd-output-list-toolbar.ts
- polymer_3/src_ts/elements/ip-reporting/pd-output-list.ts
- polymer_3/src_ts/elements/ip-reporting/pd-output.ts
- polymer_3/src_ts/elements/ip-reporting/pd-report-export-button.ts
- polymer_3/src_ts/elements/ip-reporting/pd-report-filters.ts
- polymer_3/src_ts/elements/ip-reporting/pd-report-info.ts
- polymer_3/src_ts/elements/ip-reporting/pd-reports-list.ts
- polymer_3/src_ts/elements/ip-reporting/pd-reports-report-title.ts
- polymer_3/src_ts/elements/list-view-single-indicator.ts
- polymer_3/src_ts/elements/user-profile/user-profile-dialog.ts
- polymer_3/src_ts/mixins/progress-report-utils-mixin.ts
- polymer_3/src_ts/pages/app/ip-reporting.ts
- polymer_3/src_ts/pages/unauthorized.ts
- polymer_3/src_ts/redux/reducers/clusterObjectives.ts
- polymer_3/src_ts/redux/reducers/indicators.ts
- polymer_3/src_ts/redux/reducers/localize.ts
- polymer_3/src_ts/redux/selectors/reportInfo.ts
[ch18344] Migrate elements\ip-reporting folder to Polymer3
> [ch18344] Migrate elements\ip-reporting folder to Polymer3

- polymer_3/package.json
- polymer_3/src_ts/elements/cluster-reporting/cluster-report-list.ts
- polymer_3/src_ts/elements/cluster-reporting/cluster-report-proxy.ts
- polymer_3/src_ts/elements/cluster-reporting/cluster-report-toolbar.ts
- polymer_3/src_ts/elements/cluster-reporting/cluster-reports.ts
- polymer_3/src_ts/elements/cluster-reporting/contacts-table.ts
- polymer_3/src_ts/elements/cluster-reporting/creation-modal-project-details.ts
- polymer_3/src_ts/elements/cluster-reporting/disaggregations-dropdown-widget.ts
- polymer_3/src_ts/elements/cluster-reporting/feedback-modal.ts
- polymer_3/src_ts/elements/cluster-reporting/indicator-editing-modal.ts
- polymer_3/src_ts/elements/cluster-reporting/indicator-locations-modal.ts
- polymer_3/src_ts/elements/cluster-reporting/indicator-locations-widget.ts
- polymer_3/src_ts/elements/cluster-reporting/indicator-modal.ts
- polymer_3/src_ts/elements/cluster-reporting/message-imo-modal.ts
- polymer_3/src_ts/elements/cluster-reporting/nav.ts
- polymer_3/src_ts/elements/cluster-reporting/paper-radio-group-custom.ts
- polymer_3/src_ts/elements/cluster-reporting/project-activity-table.ts
- polymer_3/src_ts/elements/cluster-reporting/project-details.ts
- polymer_3/src_ts/elements/cluster-reporting/project-list-table.ts
> wip cluster-report migration

- polymer_3/src_ts/elements/cluster-reporting/planned-action/projects/activities.ts
- polymer_3/src_ts/elements/cluster-reporting/planned-action/projects/creation-modal.ts
- polymer_3/src_ts/elements/cluster-reporting/planned-action/projects/custom-fields-widget.ts
- polymer_3/src_ts/elements/cluster-reporting/planned-action/projects/editing-modal.ts
- polymer_3/src_ts/elements/cluster-reporting/planned-action/projects/filters.ts
- polymer_3/src_ts/elements/cluster-reporting/planned-action/projects/indicators.ts
- polymer_3/src_ts/elements/cluster-reporting/planned-action/projects/overview.ts
[ch18476] Polymer3 migrate "cluster-reporting\planned-action\projects" folder
> [ch18476] Polymer3 migrate "cluster-reporting\planned-action\projects" folder

- polymer_3/src_ts/elements/cluster-reporting/analysis/analysis-filters.ts
- polymer_3/src_ts/elements/cluster-reporting/analysis/analysis-widget.ts
- polymer_3/src_ts/elements/cluster-reporting/analysis/current-progress-by-location.ts
- polymer_3/src_ts/elements/cluster-reporting/analysis/current-progress-by-partner.ts
- polymer_3/src_ts/elements/cluster-reporting/analysis/current-progress-by-project.ts
- polymer_3/src_ts/elements/cluster-reporting/analysis/indicator-bucket.ts
- polymer_3/src_ts/elements/cluster-reporting/analysis/indicator-details.ts
- polymer_3/src_ts/elements/cluster-reporting/analysis/indicators-filters.ts
- polymer_3/src_ts/elements/cluster-reporting/analysis/indicators.ts
- polymer_3/src_ts/elements/cluster-reporting/analysis/operational-presence-map.ts
- polymer_3/src_ts/elements/cluster-reporting/analysis/operational-presence-table.ts
- polymer_3/src_ts/elements/cluster-reporting/analysis/partners-by-status.ts
- polymer_3/src_ts/elements/cluster-reporting/analysis/partners-per-cluster-objective.ts
- polymer_3/src_ts/elements/cluster-reporting/analysis/partners-per-cluster.ts
- polymer_3/src_ts/elements/cluster-reporting/analysis/partners-per-type.ts
- polymer_3/src_ts/elements/cluster-reporting/analysis/progress-over-time.ts
[ch18473] Polymer3 migrate "cluster-reporting\analysis" folder
> [ch18473] Polymer3 migrate "cluster-reporting\analysis" folder

- polymer_3/src_ts/elements/cluster-reporting/response-parameters/partners/activities/filters.ts
- polymer_3/src_ts/elements/cluster-reporting/response-parameters/partners/activities/indicators.ts
- polymer_3/src_ts/elements/cluster-reporting/response-parameters/partners/activities/overview.ts
- polymer_3/src_ts/elements/cluster-reporting/response-parameters/partners/contacts/filters.ts
- polymer_3/src_ts/elements/cluster-reporting/response-parameters/partners/projects/activities.ts
- polymer_3/src_ts/elements/cluster-reporting/response-parameters/partners/projects/filters.ts
- polymer_3/src_ts/elements/cluster-reporting/response-parameters/partners/projects/indicators.ts
- polymer_3/src_ts/elements/cluster-reporting/response-parameters/partners/projects/overview.ts
[ch18639] Polymer3 migrate "cluster-reporting\response-parameters" folder
> [ch18639] Polymer3 migrate "cluster-reporting\response-parameters" folder

- polymer_3/src_ts/elements/cluster-reporting/dashboard/activities-list.ts
- polymer_3/src_ts/elements/cluster-reporting/dashboard/constrained-reports-list.ts
- polymer_3/src_ts/elements/cluster-reporting/dashboard/indicators-by-status.ts
- polymer_3/src_ts/elements/cluster-reporting/dashboard/number-of-due-reports.ts
- polymer_3/src_ts/elements/cluster-reporting/dashboard/number-of-non-cluster-activities.ts
- polymer_3/src_ts/elements/cluster-reporting/dashboard/number-of-partners.ts
- polymer_3/src_ts/elements/cluster-reporting/dashboard/number-of-projects.ts
- polymer_3/src_ts/elements/cluster-reporting/dashboard/reports-list.ts
[ch18474] Polymer3 migrate "cluster-reporting\dashboard" folder
> [ch18474] Polymer3 migrate "cluster-reporting\dashboard" folder

- polymer_3/src_ts/elements/ip-reporting/app-header.ts
- polymer_3/src_ts/elements/user-profile/profile-dropdown.ts
[ch18628] Fix header Profile dropdown.
> [ch18628] Fix header Profile dropdown.

- polymer_3/src_ts/elements/user-profile/user-profile-dialog.ts
- polymer_3/src_ts/pages/login.ts
> fix user-profile-dialog style issue

- polymer_3/src_ts/pages/app/cluster-reporting/response-parameters/clusters/activities.ts
- polymer_3/src_ts/pages/app/cluster-reporting/response-parameters/clusters/activity.ts
- polymer_3/src_ts/pages/app/cluster-reporting/response-parameters/clusters/clusters.ts
- polymer_3/src_ts/pages/app/cluster-reporting/response-parameters/clusters/disaggregations.ts
- polymer_3/src_ts/pages/app/cluster-reporting/response-parameters/clusters/objective.ts
- polymer_3/src_ts/pages/app/cluster-reporting/response-parameters/clusters/objectives.ts
- polymer_3/src_ts/pages/app/cluster-reporting/response-parameters/clusters/router.ts
- polymer_3/src_ts/pages/app/cluster-reporting/response-parameters/partners/activities.ts
- polymer_3/src_ts/pages/app/cluster-reporting/response-parameters/partners/activity.ts
- polymer_3/src_ts/pages/app/cluster-reporting/response-parameters/partners/contacts.ts
- polymer_3/src_ts/pages/app/cluster-reporting/response-parameters/partners/partners.ts
- polymer_3/src_ts/pages/app/cluster-reporting/response-parameters/partners/project.ts
- polymer_3/src_ts/pages/app/cluster-reporting/response-parameters/partners/projects.ts
- polymer_3/src_ts/pages/app/cluster-reporting/response-parameters/partners/router.ts
[ch18722] Migrate pages/cluster-reporting folder to Polymer3
> [ch18722] Migrate pages/cluster-reporting folder to Polymer3

- polymer_3/src_ts/elements/disaggregations/disaggregation-table-cell-percentage.ts
- polymer_3/src_ts/elements/disaggregations/disaggregation-table-cell-ratio.ts
- polymer_3/src_ts/elements/indicator-details.ts
- polymer_3/src_ts/elements/ip-reporting/pd-output.ts
[ch18647] Test Polymer3 IP Reporting and check if the original functionality has been preserved.
> [ch18647]Test Polymer3 IP Reporting and check if the original functionality has been preserved.

- nginx_proxy/nginx-site.conf.j2
- polymer_3/Dockerfile-bundle
- polymer_3/codefresh_polymer3.yml
- polymer_3/express.js
- polymer_3/gulpfile.js
- polymer_3/index.html
- polymer_3/package.json
- polymer_3/polymer.json
- polymer_3/src_ts/app-shell.ts
- polymer_3/src_ts/config.ts
- polymer_3/src_ts/elements/cluster-reporting/chip-date-of-report.ts
- polymer_3/src_ts/elements/cluster-reporting/planned-action/activities/filters.ts
- polymer_3/src_ts/elements/cluster-reporting/planned-action/activities/indicators.ts
- polymer_3/src_ts/elements/cluster-reporting/response-parameters/clusters/activities/filters.ts
- polymer_3/src_ts/elements/cluster-reporting/response-parameters/clusters/objectives/filters.ts
- polymer_3/src_ts/elements/cluster-reporting/response-parameters/partners/activities/indicators.ts
- polymer_3/src_ts/elements/cluster-reporting/response-parameters/partners/projects/filters.ts
- polymer_3/src_ts/elements/cluster-reporting/response-parameters/partners/projects/indicators.ts
- polymer_3/src_ts/pages/app.ts
[ch18648] Setup and test PRP build
> [ch18648] Setup and test PRP build

- polymer_3/package.json
- polymer_3/src_ts/app-shell.ts
- polymer_3/src_ts/elements/ip-reporting/authorized-officer-modal.ts
- polymer_3/src_ts/elements/ip-reporting/pd-output.ts
- polymer_3/src_ts/elements/ip-reporting/report-attachments.ts
- polymer_3/src_ts/pages/login-token.ts
- polymer_3/src_ts/pages/unauthorized.ts
- polymer_3/src_ts/redux/reducers/programmeDocumentReportsAttachments.ts
[ch18647] Fixed Ip Reporting Other Info attachments
> [ch18647] Fixed Ip Reporting Other Info attachments

- polymer_3/src_ts/elements/app-redirect.ts
> [ch18876] Page not found

- polymer_3/src_ts/pages/app/ip-reporting/pd/pd-report-sr/reporting.ts
[ch18815] Cannot submit Special Report
[ch18937] Chars counter missing in SR Narrative
> [ch18815] Cannot submit Special Report

- polymer_3/package.json
- polymer_3/src_ts/elements/ip-reporting/authorized-officer-modal.ts
- polymer_3/src_ts/elements/ip-reporting/ip-reporting-indicator-details.ts
- polymer_3/src_ts/elements/list-placeholder.ts
- polymer_3/src_ts/elements/list-view-indicators.ts
- polymer_3/src_ts/elements/list-view-single-indicator.ts
- polymer_3/src_ts/mixins/data-table-mixin.ts
- polymer_3/src_ts/mixins/pagination-mixin.ts
Bug fixes (Indicators, Authorized officer modal)
> Bug fixes (Indicators, Authorized officer modal)

- polymer_3/src_ts/elements/disaggregations/disaggregation-field.ts
- polymer_3/src_ts/elements/disaggregations/disaggregation-table-cell-percentage.ts
- polymer_3/src_ts/elements/disaggregations/disaggregation-table-cell-ratio.ts
[ch18869] Incorrect display of percentage
> [ch18869] Incorrect display of percentage

- polymer_3/src_ts/elements/disaggregations/disaggregation-modal.ts
- polymer_3/src_ts/elements/ip-reporting/authorized-officer-modal.ts
- polymer_3/src_ts/pages/app/ip-reporting/pd/pd-report.ts
- polymer_3/src_ts/styles/buttons-styles.ts
> [ch18842] Buttons misplaced

- polymer_3/src_ts/elements/confirm-box.ts
[ch18858] Console error if you cancel edit on calculation methods
> [ch18858] Console error if you cancel edit on calculation methods

- polymer_3/src_ts/elements/indicator-details.ts
- polymer_3/src_ts/elements/language-dropdown.ts
- polymer_3/src_ts/elements/report-status.ts
[ch18849] Style issues - Distance
[ch18940] Highlight location in indicator style issue
> [ch18849] Style issues - Distance, [ch18940] Highlight location in indicator style issue

- polymer_3/src_ts/styles/table-styles.ts
[ch18862] List of Reports style issue
> [ch18862] List of Reports style issue

- polymer_3/src_ts/elements/ip-reporting/pd-details-overview.ts
- polymer_3/src_ts/elements/workspace-dropdown.ts
[ch18867] Country drop-down style
> [ch18867] Country drop-down style

- polymer_3/src_ts/elements/disaggregations/disaggregation-modal.ts
- polymer_3/src_ts/elements/indicator-details.ts
[ch19045] When loading indicators in report display loading symbol.
> [ch19045] When loading indicators in report display loading symbol.

- polymer_3/src_ts/elements/ip-reporting/authorized-officer-modal.ts
[ch19101] IP-PRP: Page freezes after Submit of report
> [ch19101] IP-PRP: Page freezes after Submit of report

- polymer_3/src_ts/elements/ip-reporting/authorized-officer-modal.ts
- polymer_3/src_ts/elements/ip-reporting/pd-output.ts
[ch19129] Continuously Loading Data for Indicator Details
> [ch19129] Continuously Loading Data for Indicator Details

- polymer_3/src_ts/elements/indicator-details.ts
- polymer_3/src_ts/elements/ip-reporting/authorized-officer-modal.ts
[ch19134] On opening details for Indicator with disaggregations loading overlay vanish before UI is rendered
> [ch19134] On opening details for Indicator with disaggregations loading overlay vanish before UI is rendered

- polymer_3/src_ts/elements/error-box.ts
- polymer_3/src_ts/elements/upload-button.ts
[ch19084] IP-PRP: Import Template does not work
> [ch19084] IP-PRP: Import Template does not work

- polymer_3/src_ts/elements/app-redirect.ts
- polymer_3/src_ts/elements/labelled-item.ts
- polymer_3/src_ts/elements/workspace-dropdown.ts
- polymer_3/src_ts/pages/app.ts
- polymer_3/src_ts/pages/app/ip-reporting.ts
[ch19042] IP-PRP: Cannot switch from one workspace to another
> [ch19042] IP-PRP: Cannot switch from one workspace to another

- polymer_3/src_ts/elements/indicator-details.ts
[ch19268] Double vertical scroll bars in indicator location details
> [ch19268] Double vertical scroll bars in indicator location details

- polymer_3/src_ts/elements/cluster-reporting/chip-date-of-report.ts
- polymer_3/src_ts/elements/cluster-reporting/indicator-editing-modal.ts
- polymer_3/src_ts/elements/cluster-reporting/indicator-modal.ts
- polymer_3/src_ts/elements/cluster-reporting/planned-action/projects/creation-modal.ts
- polymer_3/src_ts/elements/cluster-reporting/response-parameters/clusters/objectives/indicators.ts
- polymer_3/src_ts/elements/cluster-reporting/response-parameters/partners/activities/indicators.ts
- polymer_3/src_ts/elements/etools-prp-chips.ts
- polymer_3/src_ts/mixins/overlay-helper-mixin.ts
[ch19371] Cannot add Custom date to indicator Report
[ch19378] Saved indicator not displayed in indicator list
> [ch19371] Cannot add Custom date to indicator Report, [ch19378] Saved indicator not displayed in indicator list

- polymer_3/src_ts/elements/cluster-reporting/planned-action/projects/creation-modal.ts
- polymer_3/src_ts/elements/list-view-single-indicator.ts
- polymer_3/src_ts/pages/app/cluster-reporting.ts
- polymer_3/src_ts/pages/app/cluster-reporting/planned-action/router.ts
- polymer_3/src_ts/pages/app/cluster-reporting/response-parameters.ts
- polymer_3/src_ts/pages/app/cluster-reporting/response-parameters/clusters/router.ts
- polymer_3/src_ts/pages/app/cluster-reporting/response-parameters/partners/router.ts
- polymer_3/src_ts/pages/app/cluster-reporting/router.ts
- polymer_3/src_ts/pages/app/ip-reporting/pd.ts
- polymer_3/src_ts/pages/app/ip-reporting/pd/pd-router.ts
[ch19396] List of Indicators - Reports redirects to Page not found
> [ch19396] List of Indicators - Reports redirects to Page not found

- polymer_3/src_ts/elements/cluster-reporting/chip-date-of-report.ts
- polymer_3/src_ts/elements/cluster-reporting/indicator-editing-modal.ts
- polymer_3/src_ts/elements/cluster-reporting/planned-action/activities/add-activity-from-project-modal.ts
- polymer_3/src_ts/elements/cluster-reporting/planned-action/activities/add-existing-activity-from-project-modal.ts
- polymer_3/src_ts/pages/app/cluster-reporting/response-parameters.ts
- polymer_3/src_ts/settings.ts
[ch19241] Refreshing the page throws user out of the app
> [ch19241] Refreshing the page throws user out of the app

- polymer_3/src_ts/elements/user-profile/user-profile-dialog.ts
- polymer_3/src_ts/pages/app/ip-reporting/pd/pd-report.ts
Fixed error on loading PD reports expected results
> Fixed error on loading PD reports expected results

- polymer_3/src_ts/elements/cluster-reporting/disaggregations-dropdown-widget.ts
[ch19375] Cannot save indicator with disaggregations
> [ch19375] Cannot save indicator with disaggregations

- polymer_3/src_ts/elements/cluster-reporting/indicator-locations-widget.ts
[ch19393] Edit Indicator redirects user to Select plan
> [ch19393] Edit Indicator redirects user to Select plan

- docker-compose.yml
added migrations to docker compose and fixed DB port issue
> added migrations to docker compose and fixed proxy port issue

- polymer_3/src_ts/elements/cluster-reporting/indicator-locations-widget.ts
- polymer_3/src_ts/elements/cluster-reporting/indicator-modal.ts
- polymer_3/src_ts/elements/json-field.ts
[ch19472] Custom Project Ratio Indicator missing Baseline + console error + style issues
> [ch19472] Custom Project Ratio Indicator missing Baseline + console error + style issues

- polymer_3/src_ts/app-shell.ts
- polymer_3/src_ts/elements/ip-reporting/ip-reporting-indicator-details.ts
- polymer_3/src_ts/elements/ip-reporting/js/pd-output-functions.ts
- polymer_3/src_ts/elements/ip-reporting/js/pd-report-info-functions.ts
- polymer_3/src_ts/elements/ip-reporting/pd-details-calculation-methods.ts
- polymer_3/src_ts/elements/ip-reporting/pd-details-overview.ts
- polymer_3/src_ts/elements/ip-reporting/pd-output.ts
- polymer_3/src_ts/elements/ip-reporting/pd-report-info.ts
- polymer_3/src_ts/elements/ip-reporting/report-attachments.ts
[ch18645] Fix lint errors from ip-reporting.
fixed lint issues in '/elements/ip-reporting'
> [ch18645] Fix lint errors from ip-reporting.

- polymer_3/src_ts/elements/cluster-reporting/cluster-report.ts
- polymer_3/src_ts/elements/cluster-reporting/cluster-reports.ts
- polymer_3/src_ts/elements/cluster-reporting/feedback-modal.ts
- polymer_3/src_ts/elements/cluster-reporting/indicator-modal.ts
- polymer_3/src_ts/elements/cluster-reporting/send-back-modal.ts
[ch19487] Reports are not displayed in Reporting Results
> [ch19487] Reports are not displayed in Reporting Results

- polymer_3/src_ts/elements/cluster-reporting/nav.ts
- polymer_3/src_ts/elements/ip-reporting/nav.ts
- polymer_3/src_ts/mixins/page-nav-mixin.ts
- polymer_3/src_ts/pages/app/cluster-reporting/response-parameters/partners/partners.ts
- polymer_3/src_ts/styles/page-nav-styles.ts
[ch1944] Add Css class to mark selected navigation menu entry.
> [ch1944] Add Css class to mark selected navigation menu entry.

- polymer_3/src_ts/elements/cluster-reporting/disaggregations-dropdown-widget.ts
- polymer_3/src_ts/elements/etools-prp-chips.ts
[ch19504] Removing a custom specific date, removes the wrong date
> [ch19504] Removing a custom specific date, removes the wrong date

- polymer_3/src_ts/elements/etools-prp-permissions.ts
[ch19517] Console error while refreshing List of reports and Report page
> [ch19517] Console error while refreshing List of reports and Report page

- polymer_3/src_ts/elements/indicator-details.ts
[ch19562] Continuously Loading Data on indicator details
> [ch19562] Continuously Loading Data on indicator details

- polymer_3/src_ts/elements/cluster-reporting/indicator-locations-widget.ts
- polymer_3/src_ts/elements/etools-prp-reset.ts
[ch19621] Locations data not valid after deleting a location.
> [ch19621] Locations data not valid after deleting a location.

- polymer_3/src_ts/elements/cluster-reporting/analysis/operational-presence-map.ts
- polymer_3/src_ts/styles/leaflet-styles.ts
Fix for build error (leaflet css)
> Fix for build error (leaflet css)

- polymer_3/src_ts/elements/cluster-reporting/analysis/operational-presence-map.ts
[ch19776] Console Error accessing Analysis
> [ch19776] Console Error accessing Analysis

- polymer_3/src_ts/elements/etools-prp-permissions.ts
[ch19727] Console Error if you hit Refresh btn from template generator
> [ch19727] Console Error if you hit Refresh btn from template generator

- polymer_3/src_ts/elements/cluster-reporting/add-response-plan-modal.ts
[ch19740] Custom Response Plan type Other style issue
> [ch19740] Custom Response Plan type Other style issue

- polymer_3/src_ts/elements/cluster-reporting/cluster-reports.ts
[ch19757] Console error after saving data for indicators
[ch19758] Submit button is disabled after details are saved for indicators
> [ch19757] Console error after saving data for indicators, [ch19758] Submit button is disabled after details are saved for indicators

- README.md
- docker-compose.yml
- polymer_3/package-lock.json
- polymer_3/src_ts/app-shell.ts
Removing migration from bk container command because with them the bk container exits
> Fix passive touch gestures warning& remove migration from bk container cmd

- polymer_3/src_ts/mixins/overlay-helper-mixin.ts
[ch19815] Page freezes at entering data for locations
> [ch19815] Page freezes at entering data for locations

- polymer_3/src_ts/elements/app-redirect.ts
[ch19873] Unauthorized page missing
> [ch19873] Unauthorized page missing

- polymer_3/src_ts/elements/cluster-reporting/add-response-plan-modal.ts
[ch19944] Response plan dropdown invalid at opening popup.
> [ch19944] Response plan dropdown invalid at opening popup.

- polymer_3/src_ts/elements/cluster-reporting/chip-date-of-report.ts
- polymer_3/src_ts/mixins/utils-mixin.ts
[ch19939] Incorrect display of year
> [ch19939] Incorrect display of year

- polymer_3/src_ts/elements/filters/date-filter/date-filter.ts
[ch20102] Clear does not work on date picker
> [ch20102] Clear does not work on date picker

- polymer_3/src_ts/elements/filters/cluster-activity-filter/cluster-activity-filter.ts
- polymer_3/src_ts/elements/filters/cluster-location-filter/cluster-location-filter.ts
- polymer_3/src_ts/elements/filters/date-filter/date-filter.ts
[ch20104] Location filter does not work
> [ch20104] Location filter does not work

- polymer_3/src_ts/elements/cluster-reporting/analysis/operational-presence-map.ts
- polymer_3/src_ts/elements/cluster-reporting/cluster-report-toolbar.ts
- polymer_3/src_ts/elements/cluster-reporting/disaggregations-dropdown-widget.ts
- polymer_3/src_ts/elements/cluster-reporting/indicator-editing-modal.ts
- polymer_3/src_ts/elements/cluster-reporting/indicator-locations-widget.ts
- polymer_3/src_ts/elements/cluster-reporting/planned-action/activities/add-activity-from-project-modal.ts
- polymer_3/src_ts/elements/cluster-reporting/planned-action/activities/add-existing-activity-from-project-modal.ts
- polymer_3/src_ts/elements/cluster-reporting/planned-action/activities/editing-modal.ts
- polymer_3/src_ts/elements/cluster-reporting/planned-action/projects/creation-modal.ts
- polymer_3/src_ts/elements/cluster-reporting/planned-action/projects/editing-modal.ts
[ch19956] Frontend linting fixes
> [ch19956] Frontend linting fixes

- polymer_3/src_ts/elements/workspace-dropdown.ts
[ch20237] Country switch does not work if the inspector is not open
> [ch20237] Country switch does not work if the inspector is not open

- polymer_3/index.html
[ch20291] Page freezes at submit
> [ch20291] Page freezes at submit

- polymer_3/src_ts/elements/cluster-reporting/planned-action/projects/filters.ts
- polymer_3/src_ts/elements/filters/date-filter/date-filter.ts
[ch20288] Incorrect date display
> [ch20288] Incorrect date display

- polymer_3/src_ts/elements/etools-prp-ajax.ts
- polymer_3/src_ts/pages/app.ts
[ch20388] Redirect to landing page in case user is not logged in
> [ch20388] Redirect to landing page in case user is not logged in

- polymer_3/src_ts/elements/cluster-reporting/cluster-report.ts
[ch20256] Submit button is disabled at Cancel
> [ch20256] Submit button is disabled at Cancel

- polymer_3/src_ts/elements/cluster-reporting/indicator-modal.ts
[ch20268] Add Project indicator as Member issues
> [ch20268] Add Project indicator as Member issues

- polymer_3/src_ts/app-shell.ts
[ch20420] Add etools-piwik to PRP
> [ch20420] Add etools-piwik to PRP

- polymer_3/src_ts/app-shell.ts
- polymer_3/src_ts/elements/workspace-dropdown.ts
- polymer_3/src_ts/pages/app.ts
- polymer_3/src_ts/pages/app/cluster-reporting/response-parameters.ts
- polymer_3/src_ts/pages/app/ip-reporting.ts
- polymer_3/src_ts/pages/app/ip-reporting/pd.ts
- polymer_3/src_ts/pages/app/ip-reporting/pd/pd-router.ts
[ch20422] Console error if you refresh report page
> [ch20422] Console error if you refresh report page

- polymer_3/src_ts/pages/unauthorized.ts
[ch19873] Unauthorized page missing (in case user has no workspace)
> [ch19873] Unauthorized page missing (in case user has no workspace)

- polymer_3/package-lock.json
- polymer_3/package.json
This reverts commit 7b0e9843f91ac4e594a81fdc84842b13b2eea460.
> Revert "Updates piwik tracker version and package-lock"

- polymer_3/package-lock.json
- polymer_3/package.json
> Updates package.json and package-lock with updated piwik component

- polymer_3/src_ts/elements/cluster-reporting/planned-action/activities/add-activity-from-project-modal.ts
- polymer_3/src_ts/elements/cluster-reporting/planned-action/activities/add-existing-activity-from-project-modal.ts
- polymer_3/src_ts/elements/cluster-reporting/planned-action/activities/creation-modal.ts
- polymer_3/src_ts/elements/cluster-reporting/planned-action/projects/creation-modal.ts
- polymer_3/src_ts/elements/cluster-reporting/response-parameters/clusters/activities/creation-modal.ts
- polymer_3/src_ts/elements/cluster-reporting/response-parameters/clusters/objectives/creation-modal.ts
- polymer_3/src_ts/elements/ip-reporting/authorized-officer-modal.ts
- polymer_3/src_ts/utils/util.ts
[ch20473] Page freeze after adding Activities as Cluster Member
> [ch20473] Page freeze after adding Activities as Cluster Member

- polymer_3/src_ts/elements/filter-list.ts
- polymer_3/src_ts/elements/ip-reporting/pd-reports-report-title.ts
[ch20469] Not showing report details after using Status filter
> [ch20469] Not showing report details after using Status filter

- polymer_3/src_ts/elements/cluster-reporting/planned-action/activities/creation-modal.ts
[ch20502] Error at creating Partner Activity without mode selected (continuously loading)
> [ch20502] Error at creating Partner Activity without mode selected (continuously loading)

- polymer_3/package-lock.json
- polymer_3/package.json
- polymer_3/src_ts/elements/cluster-reporting/add-response-plan-modal.ts
- polymer_3/src_ts/elements/cluster-reporting/indicator-editing-modal.ts
- polymer_3/src_ts/elements/cluster-reporting/indicator-modal.ts
- polymer_3/src_ts/elements/cluster-reporting/planned-action/activities/add-activity-from-project-modal.ts
- polymer_3/src_ts/elements/cluster-reporting/planned-action/activities/add-existing-activity-from-project-modal.ts
- polymer_3/src_ts/elements/cluster-reporting/planned-action/activities/creation-modal.ts
- polymer_3/src_ts/elements/cluster-reporting/planned-action/activities/editing-modal.ts
- polymer_3/src_ts/elements/cluster-reporting/planned-action/projects/creation-modal.ts
- polymer_3/src_ts/elements/cluster-reporting/planned-action/projects/editing-modal.ts
- polymer_3/src_ts/elements/cluster-reporting/response-parameters/clusters/activities/creation-modal.ts
- polymer_3/src_ts/elements/cluster-reporting/response-parameters/clusters/objectives/creation-modal.ts
- polymer_3/src_ts/elements/ip-reporting/authorized-officer-modal.ts
> [ch19962]Fix dropdown closing on clicking on scroll

- django_api/django_api/apps/unicef/exports/programme_documents.py
> Correct excel export cash transfer percentage calculation

- django_api/django_api/apps/partner/serializers.py
- django_api/django_api/apps/partner/tests/test_views.py
> Partner project total budget value handled properly

- polymer_3/src_ts/elements/list-view-single-indicator.ts
[ch20647] Edit marker brings up console error
> [ch20647] Edit marker brings up console error

- polymer_3/src_ts/elements/language-dropdown.ts
- polymer_3/src_ts/redux/reducers/localize.ts
[ch20620] UI selected language changes back to English at refresh
> [ch20620] UI selected language changes back to English at refresh

- polymer_3/package-lock.json
- polymer_3/package.json
> updated etools-dropdown

- polymer_3/src_ts/elements/cluster-reporting/add-response-plan-modal.ts
- polymer_3/src_ts/elements/filters/dropdown-filter/dropdown-filter-multi.ts
[ch20664] Clicking on vertical scroll bar closes multi-dropdown list.
> [ch20664] Clicking on vertical scroll bar closes multi-dropdown list.

- polymer_3/src_ts/elements/filters/dropdown-filter/dropdown-filter-multi.ts
[ch20702] Not showing default status filters
> [ch20702] Not showing default status filters

- polymer_3/src_ts/elements/cluster-reporting/project-activity-table.ts
[ch20608] No results found missing
> [ch20608] No results found missing

- polymer_3/src_ts/elements/cluster-reporting/response-parameters/clusters/objectives/creation-modal.ts
- polymer_3/src_ts/pages/app/ip-reporting/pd/pd-report-sr/reporting.ts
- polymer_3/src_ts/pages/app/ip-reporting/pd/pd-report.ts
[ch20789] Deleting Narrative for SR shows console error
> [ch20789] Deleting Narrative for SR shows console error

- polymer_3/src_ts/elements/ip-reporting/pd-report-info.ts
- polymer_3/src_ts/pages/app/ip-reporting/pd/pd-report-sr/reporting.ts
[ch20415] Narrative save for Special Report issue
> [ch20415] Narrative save for Special Report issue

- polymer_3/src_ts/elements/etools-prp-permissions.ts
[ch20856] PRP role with no cluster triggers permission errors
> [ch20856] PRP role with no cluster triggers permission errors

- polymer_3/src_ts/elements/cluster-reporting/planned-action/activities/creation-modal.ts
- polymer_3/src_ts/elements/cluster-reporting/planned-action/activities/editing-modal.ts
[ch20852] Add Activity as member dialog issues
> [ch20852] Add Activity as member dialog issues

- django_api/django_api/apps/partner/serializers.py
> Add psea fields to partner detail serializer

- django_api/django_api/apps/partner/models.py
- django_api/django_api/apps/partner/serializers.py
> Psea to partner serializer

- django_api/django_api/settings/base.py
need locahost redis to run tests in circle
> change redis to local host

- .circleci/config.yml
- django_api/Dockerfile
Also run `collectstatic` in container
> Add bash to backend container

- django_api/django_api/apps/indicator/serializers.py
> Define disaggregation_reported_on as ListField so default value set

- django_api/django_api/apps/partner/serializers.py
- django_api/django_api/apps/partner/tests/test_views.py
- django_api/django_api/apps/partner/views.py
> Handle missing projects for PartnerActivity updates

- polymer_3/src_ts/pages/app/ip-reporting/pd/pd-report.ts
[ch21389] Console error at submitting Special Report
> [ch21389] Console error at submitting Special Report

- polymer_3/codefresh_polymer3.yml
- polymer_3/package.json
[ch20405] Show 'buildDate' and 'revison' in package.json
> [ch20405] Show 'buildDate' and 'revison' in package.json

- django_api/Pipfile
- django_api/Pipfile.lock
- django_api/django_api/settings/dev.py
- django_api/django_api/settings/prod.py
- django_api/django_api/settings/staging.py
This may be the cause of login issues on dev/staging
> Remove allauth, does not look like it is being used.

- django_api/django_api/apps/unicef/exports/programme_documents.py
> Correct cash transfer percentage value in exports

- polymer_3/express.js
- polymer_3/polymer.json
> [ch21370] Remove es5 build

- polymer_3/src_ts/elements/ip-reporting/report-attachments.ts
> [ch21591] File upload issues

- django_api/django_api/apps/partner/serializers.py
- django_api/django_api/apps/unicef/tests/test_views.py
- django_api/django_api/apps/unicef/urls.py
- django_api/django_api/apps/unicef/views.py
> [ePD] Sync PRP users to eTools

- polymer_3/src_ts/elements/cluster-reporting/add-response-plan-modal.ts
[ch22077] Fix Add Response Plan
> [ch22077] Fix Add Response Plan

- django_api/django_api/apps/unicef/models.py
> Update pmp link

- polymer_3/src_ts/elements/ip-reporting/pd-details-overview.ts
[ch23355] IP PRP: Getting spinning wheel of death when try to click on existing PD
> [ch23355] IP PRP: Getting spinning wheel of death when try to click on existing PD

- django_api/Pipfile
- django_api/django_api/apps/core/mixins.py
> Update mixins for new b2c

- polymer_3/src_ts/elements/etools-prp-toolbar.ts
[ch18564] IP-Reporting: List of Indicators and PDF Export Issues
> [ch18564] IP-Reporting: List of Indicators and PDF Export Issues

- django_api/Dockerfile-installed
- django_api/django_api/apps/unicef/templates/progress_report_detail_pdf_export.css
- django_api/django_api/apps/unicef/templates/progress_report_list_pdf_export.css
- django_api/django_api/apps/unicef/tests/test_views.py
> PDF export tweaks to table column widths

- django_api/django_api/apps/indicator/serializers.py
> Check we have attribute value before attempting to use it

- django_api/django_api/apps/unicef/tests/test_views.py
- django_api/django_api/apps/unicef/views.py
> Add sorting to ProgrammeDocument list view

- polymer_3/src_ts/elements/ip-reporting/pd-details-overview.ts
[ch19587] IP-PRP: Special Reports numbering are now in reverse order
> [ch19587] IP-PRP: Special Reports numbering are now in reverse order

- .circleci/config.yml
> [ch24672]Circleci setup

- django_api/django_api/apps/unicef/templates/report_annex_c_pdf.html
> [ch19627] fix annex c

- django_api/django_api/apps/unicef/templates/progress_report_detail_pdf_export.html
> [ch19627] fix progress report export

- polymer_3/src_ts/endpoints.ts
- polymer_cluster/src_ts/endpoints.ts
- polymer_cluster/src_ts/pages/app.ts
> Refactor endpoints

- django_api/etools_prp/apps/unicef/exports/programme_documents.py
https://sentry.io/organizations/unicef-jk/issues/2503576343/?project=1299381&query=is%3Aunresolved
> [sentry 2503576343] fix active sheet

- django_api/etools_prp/apps/account/views.py
- django_api/etools_prp/apps/core/mixins.py
- django_api/etools_prp/apps/core/templates/unauthorized.html
- django_api/etools_prp/apps/core/views.py
- django_api/etools_prp/config/settings.py
- django_api/etools_prp/config/urls.py
> [ch26471] fix slash view

- django_api/etools_prp/apps/core/views.py
- django_api/etools_prp/config/urls.py
> redirect url

- django_api/etools_prp/apps/core/permissions.py
> [ch26736] fix permission for anonymous users

- django_api/etools_prp/apps/indicator/utilities.py
- django_api/etools_prp/apps/unicef/export_report.py
> [ch26735] invalid-xls-sheetname

- django_api/etools_prp/apps/core/permissions.py
- django_api/etools_prp/apps/unicef/views.py
> [ch27348] tweak export permissions

- .circleci/config.yml
- react/id_management_frontend/.Dockerignore
- react/id_management_frontend/.gitignore
- react/id_management_frontend/Dockerfile-bundle
- react/id_management_frontend/package-lock.json
> [ch27333][Id-Management]Refactor Dockerfile-bundle to reduce img size

- frontend_cluster/src_ts/elements/cluster-reporting/indicator-locations-modal.ts
- frontend_cluster/src_ts/elements/cluster-reporting/indicator-locations-widget.ts
- frontend_cluster/src_ts/elements/cluster-reporting/indicator-modal.ts
- frontend_cluster/src_ts/elements/cluster-reporting/planned-action/projects/creation-modal.ts
- frontend_cluster/src_ts/elements/cluster-reporting/project-details.ts
- frontend_cluster/src_ts/elements/cluster-reporting/project-list-table.ts
- frontend_cluster/src_ts/elements/cluster-reporting/reporting-indicator-details-functions.ts
- frontend_cluster/src_ts/elements/filters/cluster-location-filter/cluster-location-filter.ts
- frontend_cluster/src_ts/elements/filters/dropdown-filter/dropdown-filter-multi.ts
- frontend_cluster/src_ts/elements/filters/dropdown-filter/searchable-dropdown-filter.ts
- frontend_cluster/src_ts/elements/filters/indicator-location-filter/indicator-location-filter.ts
- frontend_cluster/src_ts/elements/filters/location-filter-multi/location-filter-multi-narrowed.ts
- frontend_cluster/src_ts/elements/filters/location-filter-multi/location-filter-multi.ts
- frontend_cluster/src_ts/elements/filters/location-filter/location-filter.ts
- frontend_cluster/src_ts/elements/filters/report-location-filter/report-location-filter.ts
- frontend_ip/src_ts/elements/filters/dropdown-filter/searchable-dropdown-filter.ts
- frontend_ip/src_ts/elements/filters/location-filter/location-filter.ts
- frontend_ip/src_ts/elements/filters/report-location-filter/report-location-filter.ts
- frontend_ip/src_ts/elements/ip-reporting/pd-details-overview.ts
[ch28147] FE: adapt to updated location model
> [ch28147] FE: adapt to updated location model

- django_api/etools_prp/apps/unicef/admin.py
> [ch28172] PRP Admin fix for AttributeError object has no attribute delete

- frontend_cluster/package-lock.json
- frontend_cluster/package.json
- frontend_ip/package-lock.json
- frontend_ip/package.json
- react/id_management_frontend/package-lock.json
- react/id_management_frontend/package.json
[ch28625] Handle security issues on repos
> [ch28625] Handle security issues on repos

- frontend_ip/src_ts/elements/ip-reporting/pd-modal.ts
[ch28596] Locations not displayed in the PD reference popup
> [ch28596] Locations not displayed in the PD reference popup

- django_api/etools_prp/apps/unicef/views.py
> [ch28655] update max number other attachments

- .circleci/config.yml
- frontend_ip/src_ts/pages/app/ip-reporting.ts
> [ch30438][ar lang]Fix profile dropdown overlap

- react/id_management_frontend/config/paths.js
- react/id_management_frontend/src/components/hoc/withSearch.js
> [ch30008] Replace deprecated 'substr' method

- django_api/etools_prp/apps/indicator/json_schemas.py
- django_api/etools_prp/apps/indicator/tests/test_views.py
> Json Validator schema fix: allow NULL value for v,d,c in indicators

- .circleci/config.yml
- frontend_ip/src_ts/elements/ip-reporting/pd-output.ts
> [ch30639] Fix icon color update after entering data on all indicator locations

- django_api/etools_prp/apps/unicef/tasks.py
- django_api/etools_prp/apps/unicef/utils.py
> [HOTFix] for process_programme_document task on target/baseline string values instead of numeric

- .circleci/config.yml
- frontend_cluster/src_ts/styles/app-theme-cluster-styles.ts
- frontend_ip/src_ts/styles/app-theme-ip-styles.ts
> [ch31022]Fix-Dropdown color theme not aligned with the rest of the app

- django_api/etools_prp/apps/unicef/serializers.py
- django_api/etools_prp/apps/unicef/tests/test_views.py
> [ch31020] Filter by location from reporting on results fix

- .circleci/config.yml
- frontend_ip/src_ts/elements/ip-reporting/pd-reports-report-title.ts
- frontend_ip/src_ts/elements/ip-reporting/progress-reports-list.ts
> [ch31042]Anchor tag style update

- .circleci/config.yml
- docker-compose.yml
- frontend_ip/src_ts/elements/list-view-single-indicator.ts
> [ch31172]Fixes after packages update- missing indicator details

- .circleci/config.yml
- docker-compose.yml
- frontend_ip/src_ts/elements/filters/dropdown-filter/dropdown-filter.ts
- frontend_ip/src_ts/elements/filters/dropdown-filter/searchable-dropdown-filter.ts
- frontend_ip/src_ts/elements/filters/location-filter/location-filter.ts
- frontend_ip/src_ts/elements/filters/report-location-filter/report-location-filter.ts
- frontend_ip/src_ts/elements/filters/reportable-filter/reportable-filter.ts
- frontend_ip/src_ts/elements/ip-reporting/indicators-filters.ts
- frontend_ip/src_ts/elements/ip-reporting/pd-report-filters.ts
- frontend_ip/src_ts/elements/ip-reporting/progress-reports-filters.ts
- frontend_ip/src_ts/elements/list-view-single-indicator.ts
> [ch31172]Fixes after packages updates -Fix 'All' being selected in dropdown

- .circleci/config.yml
- frontend_ip/src_ts/elements/ip-reporting/pd-details-overview.ts
- frontend_ip/src_ts/endpoints.ts
- frontend_ip/src_ts/pages/app/ip-reporting/pd.ts
- frontend_ip/src_ts/redux/actions/pd.ts
- frontend_ip/src_ts/redux/reducers/programmeDocuments.ts
Revert "[ch31343] [Intermittent] Continuous loading PD/SSFA Data in Programme Document"
> Revert "[ch31343] [Intermittent] Continuous loading PD/SSFA Data in Programme Document"

- django_api/etools_prp/apps/unicef/serializers.py
[ch31343] pd detail serializer
> [ch31343] pd detail serializer

- frontend_ip/src_ts/elements/etools-prp-toolbar.ts
- frontend_ip/src_ts/elements/ip-reporting/js/progress-reports-toolbar-functions.ts
- frontend_ip/src_ts/elements/ip-reporting/progress-reports-toolbar.ts
- frontend_ip/src_ts/locales.ts
[ch31611] Progress Reports - Export buttons (XLS, PDF) to be visible only when Submitted, Accepted is selected from Filters
> [ch31611] Progress Reports - Export buttons (XLS, PDF) to be visible only when Submitted, Accepted is selected from Filters

- frontend_ip/src_ts/elements/ip-reporting/pd-report-filters.ts
- frontend_ip/src_ts/elements/ip-reporting/report-filters.ts
[ch31598] All should be selected by default in filters
> [ch31598] All should be selected by default in filters

- frontend_ip/src_ts/elements/ip-reporting/pd-details-calculation-methods.ts
- frontend_ip/src_ts/elements/ip-reporting/pd-details-overview.ts
- frontend_ip/src_ts/elements/ip-reporting/pd-details-reports.ts
- frontend_ip/src_ts/pages/app/ip-reporting/pd.ts
- frontend_ip/src_ts/redux/actions/pd.ts
- frontend_ip/src_ts/redux/reducers/programmeDocuments.ts
[ch31343] [Intermittent] Continuous loading PD/SSFA Data in Programme Document
>  [ch31343] [Intermittent] Continuous loading PD/SSFA Data in Programme Document

- django_api/etools_prp/apps/indicator/tasks.py
> Fix: on process_due_reports report status

- frontend_ip/src_ts/elements/ip-reporting/js/pd-details-calculation-methods-functions.ts
- frontend_ip/src_ts/elements/ip-reporting/pd-details-calculation-methods.ts
> [ch29826]Latest for percentage

- django_api/etools_prp/apps/unicef/filters.py
- django_api/etools_prp/apps/unicef/tests/test_views.py
> PMP/PRP reports: add filter by year

- django_api/etools_prp/apps/unicef/tasks.py
- django_api/etools_prp/apps/unicef/tests/test_tasks.py
> [PMP] Unfinished Amendments block PMP&PRP sync

- frontend_ip/src_ts/elements/ip-reporting/app-header.ts
[ch32748] Fix display on My Profile dialog
> [ch32748] Fix display on My Profile dialog

- frontend_ip/src_ts/elements/ip-reporting/nav.ts
[ch33982]
https://github.com/unicef/etools-prp-common/pull/31
> [ch33982]Broken link to AMP  in PRP

- django_api/etools_prp/apps/unicef/serializers.py
ImportUserRealmsSerializer: add username for user create, email validation
> [ch33421] Sync realms from etools

- django_api/etools_prp/apps/account/tests/test_views.py
- django_api/etools_prp/apps/partner/views.py
- django_api/etools_prp/apps/unicef/serializers.py
- django_api/etools_prp/apps/unicef/tests/test_views.py
- django_api/etools_prp/apps/unicef/views.py
> [ch34011] Partner cannot submit reports

- frontend_ip/src_ts/elements/organization-dropdown.ts
> Fix errors

- django_api/etools_prp/apps/account/models.py
- django_api/etools_prp/apps/unicef/serializers.py
- django_api/etools_prp/apps/unicef/tests/test_views.py
> PRP realm sync fix: allow realms & user deactivation

- django_api/etools_prp/apps/indicator/tests/test_views.py
- django_api/etools_prp/apps/indicator/views.py
> [ch34915] Permission error toast when UNICEF user expands report indicator

- django_api/etools_prp/apps/unicef/views.py
> [ch35324] fix for float division by zero

- frontend_ip/src_ts/elements/ip-reporting/js/pd-output-list-toolbar-functions.ts
[ch34686] Missing "REFRESH" button
> [ch34686] Missing "REFRESH" button

- django_api/etools_prp/apps/core/admin.py
- django_api/etools_prp/apps/core/cartodb.py
- django_api/etools_prp/apps/core/locations_sync.py
> add rebuild tree functionality

- frontend_ip/src_ts/elements/ip-reporting/pd-output.ts
- frontend_ip/src_ts/elements/ip-reporting/report-attachments.ts
> PRP migration disaggregation

- django_api/etools_prp/apps/core/common.py
- django_api/etools_prp/apps/unicef/serializers.py
- django_api/etools_prp/apps/unicef/tests/test_views.py
- django_api/etools_prp/apps/unicef/views.py
> UNICEF acceptance rating is showing the same for Final progress report

- django_api/etools_prp/apps/unicef/views.py
> Change response for POST pd calculation-methods same as GET response

- frontend_ip/assets/i18n/ar.json
- frontend_ip/assets/i18n/en.json
- frontend_ip/assets/i18n/es.json
- frontend_ip/assets/i18n/fr.json
- frontend_ip/assets/i18n/pt.json
- frontend_ip/assets/i18n/ru.json
> [ch35187] Changed Final status labels

- django_api/etools_prp/apps/unicef/serializers.py
- django_api/etools_prp/apps/unicef/tests/test_views.py
- django_api/etools_prp/apps/unicef/views.py
[ch38014] allow blank for accepted comment
> [ch38014] SR reports can't be accepted / HR pull 

- frontend_ip/src_ts/elements/ip-reporting/pd-details-calculation-methods.ts
- frontend_ip/src_ts/redux/actions/pdIndicators.ts
[ch38031] PRP staging bugs v1, indicators tab fix
> [ch38031] PRP staging bugs v1, indicators tab fix

- frontend_ip/src_ts/elements/ip-reporting/report-attachments.ts
[ch38649] PRP dev - GPD/ Reporting on Data - delete an uploaded file
> [ch38649] PRP dev - GPD/ Reporting on Data - delete an uploaded file

- django_api/etools_prp/apps/core/api.py
- django_api/etools_prp/apps/core/locations_sync.py
> [ch39322] Adjust page size and timeout on etools locations request

- django_api/etools_prp/apps/core/tests/test_views.py
- django_api/etools_prp/apps/unicef/serializers.py
- django_api/etools_prp/apps/unicef/tests/test_views.py
> [ch38443] Filter out non-PRP groups (eg.last mile) from AMP sync

- django_api/etools_prp/apps/core/locations_sync.py
- django_api/etools_prp/apps/core/tests/test_locations.py
> [ch39322] Sync etools location: locations without geom to be created

- django_api/etools_prp/apps/unicef/ppd_sync/update_create_date_period.py
- django_api/etools_prp/apps/unicef/ppd_sync/update_create_section.py
- django_api/etools_prp/apps/unicef/tasks.py
- django_api/etools_prp/apps/unicef/tests/tests_sync/ppd/conftest.py
- django_api/etools_prp/apps/unicef/tests/tests_sync/ppd/test_main.py
> [ch37109] splitting ppd item stage3

- django_api/etools_prp/apps/unicef/ppd_sync/update_create_blueprint.py
- django_api/etools_prp/apps/unicef/ppd_sync/update_create_disaggregation.py
- django_api/etools_prp/apps/unicef/ppd_sync/update_create_expected_result.py
- django_api/etools_prp/apps/unicef/ppd_sync/update_create_location.py
- django_api/etools_prp/apps/unicef/ppd_sync/update_create_reportable.py
- django_api/etools_prp/apps/unicef/ppd_sync/update_create_reportable_location_goal.py
- django_api/etools_prp/apps/unicef/ppd_sync/update_create_section.py
- django_api/etools_prp/apps/unicef/tasks.py
- django_api/etools_prp/apps/unicef/tests/tests_sync/ppd/test_main.py
- django_api/etools_prp/apps/unicef/tests/tests_sync/ppd/test_pd_item.py
> [ch37109] Fase 5 Ultimo. Finalization

- django_api/etools_prp/apps/unicef/ppd_sync/update_create_person.py
> [ch39737] [PRP] The Authorized Officers drop-down list is empty and the report cannot be submitted

- django_api/etools_prp/apps/unicef/tasks.py
> [ch39733]-removed the function for remove duplicates

- frontend_ip/assets/i18n/ar.json
- frontend_ip/assets/i18n/en.json
- frontend_ip/assets/i18n/es.json
- frontend_ip/assets/i18n/fr.json
- frontend_ip/assets/i18n/pt.json
- frontend_ip/assets/i18n/ru.json
- frontend_ip/src_ts/elements/ip-reporting/header/user-profile-dialog.ts
[ch39602] [PRP] [My Profile] Display the correct information
> [ch39602] [PRP] [My Profile] Display the correct information

- django_api/etools_prp/apps/unicef/serializers.py
- django_api/etools_prp/apps/unicef/tests/test_views.py
> [ch39995] serializers for PD was searching for locations not in llos cp output

- frontend_ip/src_ts/elements/ip-reporting/menu/app-menu.ts
[ch40065]  [PRP GPD] Submit SR report, hide Indicators link in Navbar for Gov Partners
> [ch40065]  [PRP GPD] Submit SR report, hide Indicators link in Navbar for Gov Partners

- django_api/etools_prp/apps/core/admin.py
- django_api/etools_prp/apps/core/locations_sync.py
- django_api/etools_prp/apps/core/tests/test_locations.py
> [ch39322] PRP sync locations fix

- django_api/etools_prp/apps/unicef/filters.py
- django_api/etools_prp/apps/unicef/urls.py
- django_api/etools_prp/apps/unicef/views.py
> [ch40063] added endpoint for gpd-progress-report listing

- django_api/etools_prp/apps/unicef/filters.py
- django_api/etools_prp/apps/unicef/urls.py
- django_api/etools_prp/apps/unicef/views.py
Reverts unicef/etools-partner-reporting-portal#2115
> Revert "[ch40063] added endpoint for gpd-progress-report listing"

- django_api/etools_prp/apps/core/admin.py
- django_api/etools_prp/apps/core/locations_sync.py
- django_api/etools_prp/apps/core/serializers.py
- django_api/etools_prp/apps/core/tests/test_locations.py
- django_api/etools_prp/apps/unicef/sync/process_pd_item.py
- django_api/etools_prp/apps/unicef/sync/update_create_location.py
- django_api/etools_prp/apps/unicef/tests/tests_sync/conftest.py
- django_api/etools_prp/apps/unicef/tests/tests_sync/test_pd_item.py
Reverts unicef/etools-partner-reporting-portal#2125
> Revert "Update from staging"

- django_api/etools_prp/apps/indicator/admin.py
- django_api/etools_prp/apps/indicator/serializers.py
- django_api/etools_prp/apps/indicator/tests/test_views.py
- django_api/etools_prp/apps/unicef/exports/annex_c_excel.py
- django_api/etools_prp/apps/unicef/exports/progress_reports.py
- django_api/etools_prp/apps/unicef/exports/reportables.py
- django_api/etools_prp/apps/unicef/serializers.py
- django_api/etools_prp/apps/unicef/tests/test_views.py
> 263988 [PRP] still displays removed locations from PD indicators

- django_api/etools_prp/apps/unicef/tests/test_views.py
- django_api/etools_prp/apps/unicef/views.py
- removed filtering of statuses to include all of them
- test updated
> All statuses are now included in the reports

- django_api/etools_prp/apps/account/admin.py
- Users with 10+ realms will have read only inlines
> Users with 10+ realms will have read only inlines

- django_api/etools_prp/apps/account/tests/test_views.py
- django_api/etools_prp/apps/indicator/tests/test_views.py
- django_api/etools_prp/apps/indicator/views.py
- django_api/etools_prp/apps/unicef/serializers.py
- django_api/etools_prp/apps/unicef/tests/test_views.py
- locations now showing in report
- locations now showing in detail view of program documents 
- tests added
> Locations missing 269901

- django_api/etools_prp/apps/unicef/tests/test_views.py
> Comment test (#2158) (#2159)

- django_api/etools_prp/apps/indicator/serializers.py
- django_api/etools_prp/apps/indicator/tests/test_views.py
- django_api/etools_prp/apps/unicef/tests/test_views.py
> Revert inactive reportable locations

- django_api/etools_prp/apps/unicef/serializers.py
- django_api/etools_prp/apps/unicef/views.py
- added custom list serializer for PDs 
- removed location fetching
> removed locations from list serializer

- django_api/etools_prp/apps/core/tests/factories.py
- django_api/etools_prp/apps/unicef/sync/process_pd_item.py
- django_api/etools_prp/apps/unicef/sync/update_create_date_period.py
- django_api/etools_prp/apps/unicef/sync/utils.py
- django_api/etools_prp/apps/unicef/tests/tests_sync/test_utils.py
> refactoring: separate SR logic from QPR and HR; fix SR removing
